### ISSUE TITLE
Not populating the query variable evaluates to NULL rather than the parameter default

### ISSUE THREAD

**Issue by MattA48** [ChilliCream/hotchocolate#2305] opened 2020-09-10 16:03 UTC
**Describe the bug**
Running a GQL query containing a default parameter value will evaluate that value as NULL rather than default if no value is provided in the query variables object but the parameter is still in the query

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a query with a default parameter non-null
```
        public async Task<IEnumerable<Alert>> GetAlerts (
            string otherParameter,
            string userLanguage = "en")
```
2. Call the query with the following GQL:
```
query($otherParameter: string!
           $userLanguage: string
) { 
  getAlerts( 
    otherParameter: $otherParameter
    userLanguage: $userLanguage
) { 
... fields from return
  }
}

query variables: {"otherParameter": "test"}
```

**Expected behaviour**
Query routine called with default parameter for userLanguage

**Actual behaviour**
Query routine called with userLanguage = null, will cause unexpected execution error if the parameter is not nullable.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version Catalina (10.15.6)

**Additional context**
The expected behaviour is seen in GraphQL.NET and in whatever server implementation GitHub is running (can be seen by running the following at https://developer.github.com/v4/explorer/ (rateLimit has dryRun default = true)

```
query($dryRun: Boolean) { 
  rateLimit( dryRun: $dryRun) { 
    cost
    limit
    nodeCount
  }
}
(no Query variables set)
```

the issue can be 'corrected' by eliminating the defaulted query from the call, i.e. running with
```
query($otherParameter: string!
) { 
  getAlerts( 
    otherParameter: $otherParameter
) { 
... fields from return
  }
}

query variables: {"otherParameter": "test"}
```

**Comment by michaelstaib** [comment] 2020-09-14 23:00
The thing here is that in GraphQL you did not specify the default parameter which makes it null.

**Comment by jedigo** [comment] 2020-09-15 10:44
I think the issue is that hot Chocolate is treating missing values in the query differently from missing variables.

If you look at the note in the spec, https://spec.graphql.org/draft/#sec-Null-Value - it looks like a missing variable is not null, but it should be treated in the same way as a missing parameter, whereas hot chocolate is treating a parameter with a missing variable differently than a missing parameter altogether.

**Comment by PascalSenn** [comment] 2020-09-15 11:30
@jedigo So there are a bunch of problems with defaults for parameters of function resolvers

But first, you are right, and this is also what we do. If a default value is set and no value is provided then the default value is used. 

We take a resolver methods and compile them to resolvers on schema build time to not use any reflection during runtime. This way the execution is fast and the schema configuration API powerful. The problem with parameter defaults is that we are not aware of them. There is no way to find out what default value is set, this information is lost in the runtime. 

The only way to actually make use of these parameteter defaults would be to compile all possible combinations of the optional parameters and then execute different resolvers when different values are provided. This is not really reasonable because that would lead to a ton of types and memory usage.

It is easy to make the schema aware of the default value though:
```csharp
        public async Task<IEnumerable<Alert>> GetAlerts (
            string otherParameter,
            [DefaultValue("en")]string userLanguage = "")
```

**Comment by michaelstaib** [comment] 2020-09-25 22:26
@jedigo the better spec reference it the variable coercion in this case:

https://spec.graphql.org/draft/#sec-Coercing-Variable-Values

But also, in this case, we should not set it to null which we do. 

The default value should not be a problem actually. I will have a look at this and we will fix it we one of the next preview builds.

**Comment by michaelstaib** [comment] 2020-11-17 11:27
We are now working on this.

**Comment by michaelstaib** [comment] 2021-06-28 12:50
#3804

**Comment by michaelstaib** [comment] 2021-08-19 20:01
This is now fixed.

**Closed** 2021-08-19 21:07 UTC
Labels: 🐛 bug, 🌶️ hot chocolate
