### ISSUE TITLE
StrawberryShake. Result deserialization. Inappropriate performance issue on large arrays

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#2524] opened 2020-10-31 06:00 UTC
**Describe the bug**
Suppose the request returns a list of objects (each object is pretty easy, like, for instance, has 5 fields - strings, ints, datetimes). And the number of such objects is 100000-200000. Then it takes about 5 mins to deserialize on 16Gb RAM.

This issue is pretty critical because it makes the client, generated by StrawberryShake, practically unusable on large arrays.

**Comment by michaelstaib** [comment] 2020-12-01 14:51
@ademchenko really would love to have you involved in the work on StrawberryShake, we are ramping work up on this. The main work can be tracked here:
https://github.com/ChilliCream/hotchocolate/pull/2708

I think it will take another two weeks to put the pieces together and start with previews. If you want to get involved in the decision-making process please get in touch and we will include you in the design meetings.

**Comment by ademchenko** [comment] 2020-12-01 15:56
@michaelstaib is there an architectural document or road map or something like this to have a look? 

After a while of using StrawberryShake my main concern is the "rigidity" of generated stuff. I mean we have pretty memory-loaded items returned by graphql server and need to use the output fields very carefully. So, we optimize everywhere - if some use case needs just two of ten output fields we have to use a query with those exact two fields. Since we have a wealth number of different scenarios we have to generate lots of different versions of each request. Thus, we would actually need some natural way of customizing response objects (like IWith interfaces or something like this).

**Comment by michaelstaib** [comment] 2020-12-01 22:17
Let's do a zoom meeting this or next week. Would love to understand your use-case better.

At the moment we are tracking the redesign in a private repo... we are still researching some aspects. I think we cover now much more cases and allow an easy tie-in with System.Rx, but would love to get your perspective on things.

**Comment by tobias-tengler** [comment] 2021-05-26 06:44
Is this still an issue with version 11.2?l
I'm closing this for now, feel free to re-open.

**Closed by tobias-tengler** 2021-05-26 06:44 UTC
Labels: 🌶️ strawberry shake

**Comment by brian-tygotech** [comment] 2022-04-16 19:27
looks like this kind of got closed because of lack of activity, but i can confirm that there is a serious problem with version 12.7 of strawberry shake that means it can't be used for fetching larger datasets.

i finally got the project i'm working on to the stage that i was ready to throw some real world data at it and i immediately noticed that the memory was way way higher that i was expecting it to be. after running a memory profiler i could see that all of the memory was being consumed by dictionaries containing strawberry shake `EntityId`s.

what i did after that was take the GraphQL .NET client, use the models generated by strawberry shake with it and all of the memory issues went away. It was also significantly faster. I have a lot of RAM on my computer so the GC never kicked in, but if I were to stick this on a modest size box in the cloud one thread would be constantly consumed in the GC, so that would kill the performance even more. For comparison (and as I say the GC was never running due to RAM still being available) after I'd finished my run that processed around 5 GB of data the process had allocated over 20GB of RAM. when i reran the same run with the GraphQL .NET client it stayed under 2GB for the entire run.

the data I was fetching using the client was between 10k - 100k rows of a narrow table, so not a silly amount of data.

the problem that you have is the caching infrastructure. the only solution i can see is to either remove it completely from the generated code, or at the least to stick a flag in the runtime config to do the same.

i'm more than happy to give you a demo of the issue, am in slack.

**Comment by PascalSenn** [comment] 2022-04-16 22:04
@brian-tygotech  Thanks for the feedback. Can you copy paste this into a new issue? 

You can btw deactive the whole caching stuff if you'd like:
```json
{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "extensions": {
    "strawberryShake": {
      "name": "ConferenceClient",
      "url": "https://workshop.chillicream.com/graphql/",
      "dependencyInjection": true,
      "strictSchemaValidation": true,
      "hashAlgorithm": "md5",
      "useSingleFile": true,
      "requestStrategy": "Default",
      "outputDirectoryName": "Generated",
      "noStore": true, //<----------
      "emitGeneratedCode": true,
      "razorComponents": false,
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}
```

**Comment by brian-tygotech** [comment] 2022-04-17 14:22
@PascalSenn thanks i've reverted back to strawberry shake with `noStore: true` and the memory consumption is back to normal levels. it requires a little bit more memory than my GraphQL.NET hybrid, but no cause for concern. perf is also similar.

i think the main issue that i had was when i looked at the documentation there was nothing that mentioned this flag in the caching section https://chillicream.com/docs/strawberryshake/caching

do you still want me to create a new issue?

**Comment by michaelstaib** [comment] 2022-04-17 18:51
We designed StrawberryShake for UI components first. In UI components you would use paging and work with a reactive store. But we allow you to opt-out of this with the `noStore` option. The only issue is maybe missing documentation regarding server to server. 

If you want you can create a PR for the caching docs and add a note there.
