### ISSUE TITLE
Missing optional value in input type throws exception

### ISSUE THREAD

**Issue by svelue** [ChilliCream/hotchocolate#4354] opened 2021-10-29 06:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In contrast to V11 a mutation fails if an optional input field is not set and the field is mapped to a non nullable property.

### Steps to reproduce

1.  Checkout and start https://github.com/svelue/OptionalInputBug
2. Run `mutation{
  addBook(book: {title: "123", someNumber: 1}){
    title
    someNumber
  }
}` --> it works
3. Run `mutation{
  addBook(book: {title: "123"}){
    title
    someNumber
  }
}` --> it fails

### Relevant log output

```shell
+        "Message": "Unexpected Execution Error",
+        "Code": null,
+        "Path": {
+          "Parent": null,
+          "Depth": 0,
+          "Name": "sendData"
+        },
+        "Locations": [
+          {
+            "Line": 2,
+            "Column": 3
+          }
+        ],
+        "Extensions": null,
+        "Exception": {
+          "ClassName": "System.NullReferenceException",
+          "Message": "Object reference not set to an instance of an object.",
+          "Data": null,
+          "InnerException": null,
+          "HelpURL": null,
+          "StackTraceString": "   at lambda_method858(Closure , Object[] )\r\n   at HotChocolate.Types.InputParser.ParseObject(IValueNode resultValue, InputObjectType type, Path path, Int32 stack, Boolean defaults)\r\n   at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputField field)\r\n   at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputField field)\r\n   at HotChocolate.Types.InputParser.ParseList(IValueNode resultValue, ListType type, Path path, Int32 stack, Boolean defaults, IInputField field)\r\n   at HotChocolate.Types.InputParser.ParseLiteralInternal(IValueNode value, IType type, Path path, Int32 stack, Boolean defaults, IInputField field)\r\n   at HotChocolate.Types.InputParser.ParseLiteral(IValueNode value, IInputField field, Type targetType)\r\n   at HotChocolate.Execution.Processing.MiddlewareContext.CoerceArgumentValue[T](ArgumentValue argument)\r\n   at HotChocolate.Execution.Processing.MiddlewareContext.ArgumentValue[T](NameString name)\r\n   at HotChocolate.Execution.Processing.DirectiveContext.ArgumentValue[T](NameString name)\r\n   at lambda_method1081(Closure , IResolverContext )\r\n   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)",
+          "RemoteStackTraceString": null,
+          "RemoteStackIndex": 0,
+          "ExceptionMethod": null,
+          "HResult": -2147467261,
+          "Source": "Anonymously Hosted DynamicMethods Assembly",
+          "WatsonBuckets": null
+        },
```

### Additional Context?

https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1635433560328800

### Product

Hot Chocolate

### Version

12.0.1

**Comment by KreativJos** [comment] 2021-11-29 11:04
This is an issue for us as well. I thought it only occurred via enums...
Our current workaround is to make those types nullable, but resolving that in our BLL is quite the pain.

**Comment by PascalSenn** [comment] 2021-11-29 11:11
@KreativJos  Optional does not mean nullable. See more for context (https://github.com/ChilliCream/hotchocolate/issues/1808)

**Comment by KreativJos** [comment] 2021-11-29 11:42
@PascalSenn That was not what I was referencing to. I have GraphQLTypes which reference models with optional values:
```
descriptor.Field(t => t.AuthorType).Type<AuthorTypeEnumType>();
```

In the annotation-method, it looks like this:

```
[GraphQLType(typeof(AuthorTypeEnumType))]
public Optional<AuthorTypeEnum> AuthorType { get; set; }
```

**Comment by KreativJos** [comment] 2021-11-29 13:46
But I want to know if the user has explicitly set the field, which is what `Optional<>` is meant for...

**Comment by tobias-tengler** [comment] 2021-11-29 13:59
Sorry my bad I thought you were using Optional on object type fields and not on input object types. My bad!

**Comment by KreativJos** [comment] 2022-02-21 10:37
Do we have any ETA for this issue?
Because of this, we currently cannot switch to HC12.

**Comment by pguidoPokerAtlas** [comment] 2022-05-04 00:30
Wondering if this is stale for a reason?  Are you no longer planning to address this in an upcoming release?

**Comment by nikonthethird** [comment] 2022-08-18 14:36
Experiencing the same problem, in V11 this worked, in V12 it results in this hard to track down `NullReferenceException`.
As a workaround, we currently use the default GUID value for non-nullable `Guid`s and use reflection to map them in the database.

**Comment by michaelstaib** [comment] 2022-08-19 08:57
This is a bug. The issue is that the input parser assumes a Nullable<int> but finds an in as a prop. I am working on this now.

**Comment by michaelstaib** [comment] 2022-08-19 09:38
https://github.com/ChilliCream/hotchocolate/pull/5317

**Closed** 2022-08-19 09:42 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Type System

**Comment by michaelstaib** [comment] 2022-08-19 10:38
This is now fixed and integrated into 12.13.0-preview.2

**Comment by nikonthethird** [comment] 2022-08-22 10:58
Thank you very much, we tested it and it appears the HotChocolate 11 behavior has been restored.

**Comment by accarin** [comment] 2022-08-22 13:37
Thanks a lot. The 12.13.0-preview.2 package seems to be fixing the described problem for my team as well!

I'm finally able to remove all the descriptor.DefaultValue / reflection shenanigans we've been using as a workaround.
