### ISSUE TITLE
Subscription is not working in MapGraphql Extension while using with RequireAuthorization

### ISSUE THREAD

**Issue by user321-creator** [ChilliCream/hotchocolate#3074] opened 2021-02-18 07:54 UTC
Hi,
    We are trying to load schema only if the Authorization Header is valid.If the Authorization token is not valid.,it should'nt load schema. To implement this case, I m using RequireAuthorization in MapGraphql Extension and its working fine as expected for Queries and Mutations.But when it comes to subscription.,it results in subscription failure with error "Could not connect to websocket endpoint". 

Expected Behaviour :
             Subscription should start listening to the topic.

 Startup File: [Startup.txt](https://github.com/ChilliCream/hotchocolate/files/6001153/Startup.txt)

**Comment by PascalSenn** [comment] 2021-02-18 08:21
closing as a duplicate of #3003

**Closed by PascalSenn** 2021-02-18 08:21 UTC
