### ISSUE TITLE
Field annotated using Serial, UsePaging and UseProjections hangs, if field is queried more than once in a single query

### ISSUE THREAD

**Issue by syedqutub** [ChilliCream/hotchocolate#4236] opened 2021-09-15 17:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,
when multiple queries are executed , if there is a query with [UsePagging] attribute. it willl go non responsive.(inifinte loading symbol). i have serial execution enabled by default.

### Steps to reproduce

1. enable serial execution
2. call multiple queries with 2 queries that have [UsePagging] muddleware

### Relevant log output

```shell
i saw the sql generated for 2 seperate queries but no logs.
```

### Additional Context?

nothing more.

### Product

Hot Chocolate

### Version

12.0.0-rc.7

**Comment by tobias-tengler** [comment] 2021-09-16 06:47
From the use of SQL in your report I assume you are using Entity Framework with our HotChocolate.Data.EntityFramework package, correct? 
Your usage of the word "query" is also a bit confusing to me. You mean you have two resolvers annotated with UsePaging and you execute something like the following, correct?

```graphql
{
  firstPagingField {
    nodes {
      id
    }
  }
 secondPagingField {
    nodes {
      id
    }
  }
}
```

Could you please share a minimal code example which reproduces the issue? Please also include the exact query you sent to the GraphQL server to cause the issue. Thanks :)

**Comment by michaelstaib** [comment] 2021-09-16 08:58
yes ... also cannot infer the issue :) Can you provide a repro showing your issue?

**Comment by syedqutub** [comment] 2021-09-17 21:36
try runing this project https://github.com/syedqutub/GraphQlTest
query is `
query{
  a:speakers{nodes{id,name}}
  b:speakers{nodes{id,name}}
}`

**Comment by tobias-tengler** [comment] 2021-09-18 06:10
Using `ScopedService` while not using the `UseDbContext` middleware doesn't work. When you add the DbContext as a scoped service and not using the pooled factory, you need to grab the DbContext from the Dependency Injection container using the `Service` attribute.

**Comment by syedqutub** [comment] 2021-09-18 06:52
Sorry alot for the inconvenience. i push an old code of `[ScopedService]` attribute attached.. i have updated the repo to `[Service]` and issue still exists.
Thanks alot!!

**Comment by tobias-tengler** [comment] 2021-09-18 07:13
I'm able to reproduce this using rc.9, also while using v5.0.10 of the EntityFramework packages.

The issue seems to be the combination of Serial + UsePaging + UseProjection.

**Comment by michaelstaib** [comment] 2021-09-20 12:12
@tobias-tengler can you attach the code?

**Comment by tobias-tengler** [comment] 2021-09-20 12:24
@michaelstaib I used the code he attached and just changed the version of the HC packages to rc.9.

**Comment by syedqutub** [comment] 2021-09-20 13:25
@tobias-tengler  yes if you use seperate resolvers with these attributes bug will appear.we are facing this in our current in development project. also can i get a status update for this :).

Thanks alot!

**Comment by michaelstaib** [comment] 2021-09-20 16:24
There are a couple of issues with this one. I will fix them with the next rc tonight. Thanks you for reporting this one.

**Comment by kolpav** [comment] 2021-09-22 06:49
@michaelstaib I have similar problem but I am making the query hang by not including `IsProjected` field. You can take a look at my repo [here](https://github.com/kolpav/HotChoco/tree/projection-bug) everything you need to reproduce the issue is in readme. I can create new issue if my problem is unrelated to this issue.

**Comment by syedqutub** [comment] 2021-09-23 09:18
@michaelstaib just to let you know, our Frontend team faces this issue in apollo client JS when executing only a single query.

Thanks

**Comment by michaelstaib** [comment] 2021-09-24 14:56
This one os now fixed.

**Closed** 2021-09-24 21:47 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data

**Comment by kolpav** [comment] 2021-09-25 22:30
@michaelstaib Confirming it works now, thank you! 👍
