### ISSUE TITLE
Rounds a Long Type when passing as variable

### ISSUE THREAD

**Issue by cbrownfloow** [ChilliCream/hotchocolate#5253] opened 2022-07-22 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you write a query that using a long type and pass that type as graphQL variable, it rounds the variable.  For example long value 553631506457470976 is changed to 553631506457471000

When you dont use a graphQL variable the value is correct and not rounded down and the correct value returned 553631506457470976

### Steps to reproduce

1.  Run the query and everything is fine
 
**Query**
```
query roadSpeeds {
  segmentSpeeds(
    speedFilterInput: {
      regionCodes: "E14000854"
      year: 2021
      dayPeriod: WEEKDAY
      segmentIds: 553631506457470976
      aggregationPeriod: ANNUAL
    }
  ) {
    segmentId
  }
}
```

2. Run the same query with query variables, when it hits the query the segmentIds has now been changed to **553631506457471000** from **553631506457470976**

**Query**
```
query ($speedFilter: SpeedFilterInput!) {
  segmentSpeeds(speedFilterInput: $speedFilter) {
    segmentId
  }
}
```
**Query Variables**
```
{
  "speedFilter":{
    "regionCodes":  "E14000854",
		"year": 2021,
    "aggregationPeriod": "ANNUAL",
    "segmentIds": 553631506457470976
  }
}
```
![image](https://user-images.githubusercontent.com/100694305/180414214-3d1a2782-6658-4f58-88f7-81d7f2341e31.png)

### Product

Hot Chocolate

### Version

12.12.1

**Comment by PascalSenn** [comment] 2022-07-22 11:24
@cbrownfloow this is not a problem of hotChocolate. This is a problem of JS :) 
![image](https://user-images.githubusercontent.com/14233220/180429546-afed97b9-d7df-4785-af63-7b8f3f85681d.png)

**Comment by michaelstaib** [comment] 2022-07-22 12:43
Closing this issue since its not a bug.

**Closed by michaelstaib** 2022-07-22 12:43 UTC
Labels: 🌶️ hot chocolate

**Comment by PascalSenn** [comment] 2022-07-28 09:00
@cbrownfloow  Exactly :) As soon as there is some Number somwhere in JS it losses the precision. This will happen in any JS based editor. If you e.g. just send the request as a string the precision will not be lost

The problem is ocuures as soon as  the value is evaluated as a number in JS. This could be by assigning it to a variable, `JSON.parse & JSON.stringify` etc.
