### ISSUE TITLE
Startup performance

### ISSUE THREAD

**Issue by iamgmd** [ChilliCream/hotchocolate#1283] opened 2019-12-13 04:58 UTC
I have a code generated hot chocolate graphql server that has been scaffolded against an existing database. The code generated 338 models and repositories and a single QueryType with 2 fields per model, a resolver GetAll and GetById. The GetAll makes use of usePaging, useFiltering and useSorting.

The startup time is approx 10 minutes in production mode. I recognise that hot chocolate infers paging, filtering and sorting through the models and some of my models are quite large, 200+ fields but if I take out paging, filtering and sorting, the startup time reduces to approx 30 seconds which is great.

I wondered if anyone else has come across performance issues with paging, filtering and sorting and maybe, if anyone has any ideas of what I could try to reduce the startup time. Afterall, my API is going to suck if I cannot have these features.

I am using 11.0.0-preview.65 with dotnet core 3.1. I have tried 10.2.0 which yielded a similar outcome.

**Comment by michaelstaib** [comment] 2019-12-13 06:04
Hi @iamgmd, 

this is not good :)

I wonder what the issue is. There must be something wrong with the way the types are inferred.

Can you post some code?

**Comment by iamgmd** [comment] 2019-12-13 06:16
Thanks for the quick reply michael, as requested:

Startup.cs

```
            services.AddScoped<AccountRepository>();
            ....

            services.AddDataLoaderRegistry();

            services.AddGraphQL(SchemaBuilder.New()
            .AddQueryType<QueryType>()
            );
```

QueryType.cs

```
           descriptor.Field("accounts")
            .Resolver(ctx => ctx.Service<AccountRepository>().GetAll())
            .Type<ListType<AccountGraphQLType>>()
            .UsePaging<AccountGraphQLType>().UseFiltering().UseSorting();

            descriptor.Field("account")
            .Argument("accountId", a => a.Type<NonNullType<StringType>>())
            .Resolver(ctx => ctx.Service<AccountRepository>().GetById(Guid.Parse(ctx.Argument<string>("accountId"))));

            .....
```

AccountGraphQLType.cs

```
 public class AccountGraphQLType : ObjectType<Account>
    {
        protected override void Configure(IObjectTypeDescriptor<Account> descriptor)
        {
            descriptor.Field(t => t.AccountCategoryCode).Type<IntType>();

            descriptor.Field(t => t.AccountClassificationCode).Type<IntType>();

            descriptor.Field(t => t.AccountId).Type<IdType>();

            descriptor.Field(t => t.AccountNumber).Type<StringType>();
            ......
        }
   }
```

Let me know if you need anymore.

**Comment by michaelstaib** [comment] 2019-12-13 11:50
```
 descriptor.Field("accounts")
            .Resolver(ctx => ctx.Service<AccountRepository>().GetAll())
            .Type<ListType<AccountGraphQLType>>()
            .UsePaging<AccountGraphQLType>().UseFiltering().UseSorting();
```

When you use paging you do not need to specify the Type... paging will do that.

```
 descriptor.Field("accounts")
            .Resolver(ctx => ctx.Service<AccountRepository>().GetAll())
            .UsePaging<AccountGraphQLType>().UseFiltering().UseSorting();
```

This is not the error though :) just a recommendation ;)

**Comment by iamgmd** [comment] 2019-12-13 12:28
Just run some rough timings. All running VS2019 v16.4.1 in Debug upto Playground showing.

- Paging, Filtering, Sorting: 10m
- Filtering, Sorting: 1m 40s
- Sorting: 43s
- None: 17s

VS2019 resting memory was approx 3GB. I did see memory usage between 3GB-5GB while waiting for playground to show and then a large surge of up anywhere between 5GB-10GB. I dont know if this is significant or not and definately real diagnostics. I have 32GB of memory and there are no crashes, just seems to take ages. I am going to port the code to another machine and run the tests there, just to see if there is any comparison.

**Comment by iamgmd** [comment] 2019-12-13 12:48
Michael, if it helps and you have the time, I can email you my code. I can't include the DB but there should be enough there for you to see first-hand what I am up against. I really want to use Hot Chocolate for this project but I have to make a decision soon. I am worried about performance of starting up the server with what I have and I haven't included enums or relationships into the models and types yet. Anyway, let me know. Geoff.

**Comment by michaelstaib** [comment] 2019-12-13 22:28
@iamgmd that would be great. This way we could much easier see what the issue is. Can you get onto slack?

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Comment by iamgmd** [comment] 2019-12-14 02:58
Michael,

 

That is now done, you should have a message in slack with the code base attached.

 

Please let me know if you need anything else.

 

Regards,

 

Geoff.

**Comment by michaelstaib** [comment] 2019-12-14 10:55
I will have a look at the weekend. We are currently working on the type discovery so, this issue fits right in there.

**Comment by michaelstaib** [comment] 2020-01-06 14:35
#1330

**Comment by michaelstaib** [comment] 2020-11-11 09:40
I am closing this since we have pretty much fixed this one. We will do more startup performance improvements with the coming versions by integrating source generators, which will defer a lot of work to the build time.

**Closed by michaelstaib** 2020-11-11 09:40 UTC
Labels: :beetle: bug, 🌶 hot chocolate
