### ISSUE TITLE
Error Reading JObject from JsonReader

### ISSUE THREAD

**Issue by ronnyek** [ChilliCream/hotchocolate#182] opened 2018-07-24 16:34 UTC
**Describe the bug**
Just trying to get the bare minimum example of hotchocolate.io stuff running, fired up a new project with the starwars template. I then pointed graphiql at it, and it seems like somewhere things go south in trying to get the metadata for the schema.

I'm unsure this is specifically a problem with starwars sample specifically, but also might be a misunderstanding on how graphiql tool works. I tried several queries, but seems like its trying to do its introspection query before anything else anyway.

In analyzing what graphiql is sending to the starwars app, its get request to http://localhost:port/?query=
```
    query IntrospectionQuery {
      __schema {
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          locations
          args {
            ...InputValue
          }
        }
      }
    }

    fragment FullType on __Type {
      kind
      name
      description
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  &variables="{}"
```

**To Reproduce**
1. Initialize new starwars example
2. Run graphiql with the endpoint set to the hostname and port, dotnet run is using
3. Attempt to run anything in the user interface
4. Observe failure, and failure in the console
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 4.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at HotChocolate.AspNetCore.GetRequest.ReadRequest(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddleware.HandleRequestAsync(HttpContext context, QueryExecuter queryExecuter, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.QueryMiddleware.Invoke(HttpContext context, QueryExecuter queryExecuter)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Expected behavior**
Probably return schema information provided by starwars example

**Additional context**
I additionally tried updating to the very latest version of hotchocolate.io, and found that it was reporting the same errors.

**Comment by michaelstaib** [comment] 2018-07-24 17:08
Hi @ronnyek  I will have a look at it tonight. The schema introspection query should be no problem. GraphiQL runs it to get a schema description in order to provide some autocompletion.

Which version of HotChocolate are you using?

**Comment by michaelstaib** [comment] 2018-07-24 17:08
Sorry, just read you are using 0.3.0.

**Comment by ronnyek** [comment] 2018-07-24 17:12
well I tried with 0.3.0 as I believe thats what the startwars template chose by default, but tried upgrading to 0.4.0-preview-1 and it did the very same thing

**Comment by michaelstaib** [comment] 2018-07-24 17:15
OK, found the issue. There seems to be an issue when the introspection query is send over HTTP Get. If you set your GraphiQL to use HTTP Post every thing will be fine.

Nevertheless we will fix the introspection issue with the HTTP Get request.

**Comment by michaelstaib** [comment] 2018-07-24 17:19
Hey @glucaci could you have a look at this? It seems that the introspection query does not work over HTTP Get. GraphiQL has no problem once it got the schema via HTTP POST to send queries via HTTP GET.

**Comment by michaelstaib** [comment] 2018-07-24 17:20
@glucaci: Seems to be an encoding issue.

**Comment by michaelstaib** [comment] 2018-07-24 17:29
@ronnyek does it work for you with HTTP Post for now? The next release version is planned for end of this week. We'll include the fix into that version.

**Comment by ronnyek** [comment] 2018-07-24 17:32
This indeed seems to be fixing the situation... I gotta figure out right queries to make sure its returning data, but seems to be throwing appropriate responses when I issue incorrect queries and not throwing a ton of exceptions on console

**Comment by ronnyek** [comment] 2018-07-24 18:01
Was able to query and was able to get what I would  expect after playing with it a bit more.

**Comment by michaelstaib** [comment] 2018-07-24 18:51
@glucaci I have added a test on the branch https://github.com/ChilliCream/hotchocolate/tree/Bug182 it seems that the issue is caused by two quotes. The variables are send like the following `"{}"` which causes newtonsoft to throw a parsing exception.

**Comment by glucaci** [comment] 2018-07-27 07:30
Hi @ronnyek,
Here it's a valid payload for a introspection query:
```
{
    "query": "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n",
    "variables": {},
    "operationName": "IntrospectionQuery"
}
```
The "variables" has no quotes, as you could also find on POST Request example from GraphQL https://graphql.org/learn/serving-over-http/

**Comment by michaelstaib** [comment] 2018-07-27 07:31
Hi @ronnyek,

we have investigated this issue and come to the conclusion that this issue is a bug in many graphiql apps. The GraphiQL app I am using just fixed this issue https://github.com/skevy/graphiql-app/pull/60 but they still haven't released that fix so far.

The issue that happens is that the GraphiQL apps are sending the variables in the get request with quotes. Basically `....&variables="{}"`where it is specified that the variables have to be send without scopes.

They basically serialize the dictionary invalidly, here is their fix:

```javascript

 return fetch(url + "query=" + encodeURIComponent(graphQLParams['query']) + "&variables=" + encodeURIComponent(graphQLParams['variables']), {
 return fetch(url + "query=" + encodeURIComponent(graphQLParams['query']) + "&variables=" + encodeURIComponent(JSON.stringify(graphQLParams['variables'])), {

```

I will close this issue since it is not a bug in our backend.

Thanks for reporting this.

**Closed** 2018-07-27 07:32 UTC
Labels: question

**Comment by streamtree** [comment] 2019-01-29 01:08
This is still a problem in 0.5.2. GET throws the exception, POST runs it without any issues.

**Comment by michaelstaib** [comment] 2019-01-29 07:58
Hi @streamtree,

what product are you referring to with version 0.5.2?

**Comment by streamtree** [comment] 2019-01-30 17:44
@michaelstaib Sorry about that, I was going off the latest version of HotChocolate as posted on hotchocolate.io. I'm using the latest Nuget version, 0.6.11.

**Comment by michaelstaib** [comment] 2019-01-31 15:01
https://github.com/ChilliCream/hotchocolate/issues/567
