### ISSUE TITLE
Simple Patching Operations

### ISSUE THREAD

**Issue by tunurgitr** [ChilliCream/hotchocolate#1517] opened 2020-03-05 20:43 UTC
**Is your feature request related to a problem? Please describe.**
It's hard to do simple update operations.

**Describe the solution you'd like**
#1326 and I'm wondering if we could do something to help support a simpler case. This use-case assumes you're only "patching" root level properties, which I think is a fairly large segment of use cases.

What if we could do something like this:
```csharp
// for this class >>>
public class User
{
    public Guid Id { get; set; }
    public string FirstName { get; set; }
    public string? MiddleName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }
    public DateTime CreatedUtc { get; set; }
}
// here's a new kind of input type >>>
public class UserUpdateInputType : UpdaterInputType<User>
{
    protected override void Configure(UpdaterInputType<Object> descriptor)
    {
        descriptor.Ignore(x => x.Id);
        descriptor.Ignore(x => x.CreatedUtc);
        descriptor.ExplicitlyBindFieldsAsOptional();
        // you could also call out fields one-by-one
        // I'd say here you can only add fields that are:
        // - properties in the C# class 
        // - have public setters or are params to the constructor
    }
}
[ExtendObject("MutationRoot")]
public class UserMutations
{
    // "input" is inferred to be an input type in the schema on UserUpdateInputType
    // each of the remaining fields would be declared as optional
    // the actual injected interface wouldn't expose the actual "User", just a method
    public async Task UserUpdate(Guid id, IUpdater<UserUpdateInputType,User> input)
    {
        var user = _repo.Load(id);
        _repo.Save(updater.Update(user));
    }
}
```
**Describe alternatives you've considered**
- Using manual classes and `Optional<T>` is annoying

In some cases we may be able to do this PCF without the separate `UserUpdateInputType`. For example, if the create and update operations all operate on the same fields.

**Comment by leonardoporro** [comment] 2020-05-20 01:35
We could use a proxy to track which fields has been set, like this one: [ChangeTracking](https://github.com/joelweiss/ChangeTracking). 
I made one myself, much more simpler, using emit.
It's fast and strongly-typed, better than using a dictionary.
By changing the type (using Argument) to the proxy type, hotchocolate correctly deserializes to my proxy class and I can check which values have been set.
The problem is that it won't work recursively, because I need that every object created passes through my logic to create the proxy (or not).
Is there any point where we can inject an instance factory?
Is ActivatorHelper.CreateNewInstance doing that? could it be public?
Thanks!

**Comment by michaelstaib** [comment] 2020-05-20 06:33
Hi @leonardoporro we are currently adding new capabilities to the serialization for spatial types. Once these are in you can override the deserialization handling.

**Comment by leonardoporro** [comment] 2020-05-20 15:01
@michaelstaib Thanks for the answer! btw, hot chocolate is awesome. I'm new to it and have been trying to deserialize the input document on my own, by following the argument coercion routines, but couldn't make it work (without changing the code and with the limited time I've invested).
Is there any way to do that? Could you point me to the right direction? Should I wait for the new capabilities? 
Thanks again

**Comment by leonardoporro** [comment] 2020-05-20 15:29
PD: If we can define Type and Implementation we would also be able to deserialize to interfaces.

**Comment by PascalSenn** [comment] 2022-03-14 11:38
Closed in favour of : https://github.com/ChilliCream/hotchocolate/discussions/4845

**Closed by PascalSenn** 2022-03-14 11:38 UTC
Labels: 🌶️ hot chocolate
