### ISSUE TITLE
Cannot have a class named Subscription, causes field resolution to fail

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#1462] opened 2020-02-10 20:00 UTC
I have the following types defined
![image](https://user-images.githubusercontent.com/2817488/74185024-d46a9380-4c15-11ea-8879-0d914db7a443.png)

but when trying to access the field using this query
```
{
  viewer{
    userUnsubscribes{
      subscriptionId
      isOptoutOfSms
      isOptoutOfEmail
      subscription{
        name
        description
      }
    }
  }
}
```
i get this error
```
"errors": [
    {
      "message": "The field `name` does not exist on the type `Query`.",
      "locations": [
        {
          "line": 1,
          "column": 20
        }
      ],
      "extensions": {
        "remote": {
          "Exception": null,
          "message": "The field `name` does not exist on the type `Query`.",
          "locations": [
            {
              "line": 1,
              "column": 20
            }
          ]
        }
      }
    },
```

if i rename my class from Subscription to anything else it works as expected

**Comment by michaelstaib** [comment] 2020-02-18 18:59
We are moving this to 11. We will definitely fix it.

**Comment by hrai** [comment] 2020-09-27 07:26
I'd love to raise a fix for this if I can get some directions @michaelstaib

**Comment by tobias-tengler** [comment] 2021-05-26 07:08
Duplicate of #3571.

**Closed** 2021-05-26 07:09 UTC
Labels: 🌶️ hot chocolate, 🐛 bug
