### ISSUE TITLE
Subscriptions not working with graphql-ws message types in HC 13

### ISSUE THREAD

**Issue by nikolai-mb** [ChilliCream/hotchocolate#5339] opened 2022-08-24 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm attempting to consume subscriptions from a react app using the graphql-request package, which recently got [subscription support](https://github.com/prisma-labs/graphql-request/issues/77).

I'm unable to retrieve any data, seemingly because the HC server expects the message type to be "start", while the official graphql-ws specification says that the type is "[subscribe](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#subscribe)".

Subscriptions work correctly in banana cake pop, but looks to be using the "start" type.
For testing, i have created a simple "numberGenerated" subscription method that publishes a random number every second.

BCP produces the following messages:
![image](https://user-images.githubusercontent.com/35340657/186444294-4e585280-35aa-4bf2-a877-2b9827631c23.png)

React app:
![image](https://user-images.githubusercontent.com/35340657/186443687-4104a9db-6715-416f-ae57-57ab80005d4c.png)
Socket is then immediately closed by the server.

Both network requests have the same WS headers
Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Version: 13
Upgrade: websocket

Debugging this with postman i see that HC drops the websocket connection with the following message: "Invalid message type."
![image](https://user-images.githubusercontent.com/35340657/186444062-ff13f58a-a1f6-4eda-8928-a297a4ee36a0.png)

Because the graphql-ws specification is fixed, it's not possible to override the message type in the package i'm using.

Please let me know if i have overlooked something obvious here, or if you need more information.

### Steps to reproduce

1. Create HC application with a simple subscription
2. Attempt to subscribe using the message type "subscribe".

### Product

Hot Chocolate

### Version

13-preview.33

**Comment by tobias-tengler** [comment] 2022-08-29 07:57
I can confirm that using the reference implementation (`graphql-ws`) in a React application works just fine for us in combination with the same Hot Chocolate version you provided:

![image](https://user-images.githubusercontent.com/45513122/187149980-fc17bf3f-e04a-49bf-88ac-47c9460298d9.png)

The value of the `Sec-WebSocket-Protocol` should be `graphql-transport-ws` according to [the specification](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#successful-connection-initialisation).

You are likely seeing the `start` message in BCP, since BCP also supports the legacy [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) (Apollo WebSocket) protocol, which uses the `graphql-ws` subprotocol in the `Sec-WebSocket-Protocol` header.

You can switch to the "real" `graphql-ws` in the connection settings (gear icon): 

![image](https://user-images.githubusercontent.com/45513122/187150483-11567ae6-3113-4896-9617-b80b8d93eaa4.png)

If you switch the header to `graphql-transport-ws` in Postman you should see it working.

Closing this as it seems to me that the fault lies with the library you are using, which is sending the wrong subprotocol header.

**Closed by tobias-tengler** 2022-08-29 07:57 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Subscriptions
