### ISSUE TITLE
SQL Server: Unable to resolve field, the connection was closed

### ISSUE THREAD

**Issue by alnw** [ChilliCream/hotchocolate#4756] opened 2022-02-13 08:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This bug happens only on SQL Server with SqlConnection, to make Hot Chocolate unable to use at all. The error is about the dbcontext closed too early (sharing dbcontext) even using Pooled and DbContextFactory, creating new dbcontext every action and await on them. The problem happens 50/50 chance happen. Tried on SqlLite is fine, so only happen when use Sql Server.

### Steps to reproduce

1. Clone https://github.com/ChilliCream/graphql-workshop

2. Got to Step 8, switch to use SqlServer instead of SqlLite

3. At Startup.cs

```csharp
            services.AddDbContextFactory<ApplicationDbContext>(
                (s, b) =>
                {
                    var connection = new SqlConnection
                    {
                        ConnectionString = "Server=(localdb)\\mssqllocaldb;Database=ConferenceDB;MultipleActiveResultSets=True;"
                    };

                    b.UseSqlServer(connection);
                });
```

4. Launch BCP,  run the query with 2 or more resolvers, eg:

```graphql
query {
  sessions {
    nodes {
      title
      attendees {
        firstName
      }
      speakers {
        name
        sessions {
          title
        }
      }
      track {
        name
      }
    }
  }
}
```

5 . Try to run couple times, you will see error 
The connection was not closed. The connection's current state is open.

### Relevant log output

```shell
"errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 10,
          "column": 9
        }
      ],
      "path": [
        "sessions",
        "nodes",
        0,
        "speakers",
        0,
        "sessions"
      ],
      "extensions": {
        "message": "The connection was not closed. The connection's current state is open.",
        "stackTrace": "   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\r\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\r\n   at ConferencePlanner.GraphQL.Types.SpeakerType.SpeakerResolvers.GetSessionsAsync(Speaker speaker, ApplicationDbContext dbContext, SessionByIdDataLoader sessionById, CancellationToken cancellationToken) in C:\\Users\\alwo\\source\\repos\\GraphQL\\GQL-Workshop\\SQLDB.NET5\\GraphQL\\Types\\SpeakerType.cs:line 40\r\n   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)\r\n   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ]
```

### Additional Context?

I have created another sample to demonstrate this issue: https://github.com/alnw/HCContoso

### Product

Hot Chocolate

### Version

12.5

**Comment by tobias-tengler** [comment] 2022-02-13 08:25
Why are you instantiating the `SqlConnection` yourself? This might not be the issue, but I have not seen the usage of `SqlConnection` outside of really barebone implementations using `SqlCommand`. Unless there is a specific reason you are doing this, I would suggest changing your code to this:

```csharp
services.AddDbContextFactory<ApplicationDbContext>( (b) => b.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=ConferenceDB;MultipleActiveResultSets=True;"));
```

This is just speculation on my part since normally the `SqlConnection` has to also be cleaned up and I'm not sure how nice it plays with the `DbContextFactory`.

**Comment by alnw** [comment] 2022-02-13 23:04
@tobias-tengler Woooo !! Thanks for your prompt response. You are correct!!!! Looks like once I use your suggestion, my demo project seems working. This is great news!

However in our production environment we are using that for access token, here is the sample code 

 var tokenProvider = new AzureServiceTokenProvider("....");
                    var connection = new SqlConnection
                    {
                        ConnectionString = "connection-string",
                        AccessToken = tokenProvider.GetAccessTokenAsync(".....").Result,
                    };

Do you know why this could fail when using HC?

**Comment by tobias-tengler** [comment] 2022-02-14 03:48
I looked around a bit and found that generally the `AccessToken` will be set from within an interceptor, when connecting to the Database. I even found this example regarding what you are trying to do: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-connection-interception-for-sql-azure-authentication-using-aad

With this you can continue using my code from above and also set the `AccessToken`, without having to manage the `SqlConnection` yourself. Just copy over the interceptor from the example, make your necessary changes and call `.AddInterceptor(new AadAuthenticationInterceptor())` after the `UseSqlServer(...)`.

I'm closing this issue now, since I suspect the behavior was caused by the pooled DbContext factory itself and not Hot Chocolate, so it's more of an EF Core issue. Feel free to report back whether what I proposed is working for you or what you ended up doing in the end though, as reference for other developers. :)

**Closed by tobias-tengler** 2022-02-14 03:48 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: EntityFramework

**Comment by alnw** [comment] 2022-02-14 20:21
Thanks @tobias-tengler, yes the solution you proposed is promising. I think we should all avoid using SqlConnection as HC suggested using Pooled DbContext, this should be noted somewhere in HC. Thanks a lot for this issue, really appreciate it!
