### ISSUE TITLE
AutoMapper ProjectTo - "Argument types do not match" Error on non String 2nd level graph query

### ISSUE THREAD

**Issue by twilly86** [ChilliCream/hotchocolate#3008] opened 2021-02-07 22:00 UTC
**Describe the bug**
I am trying to get AutoMapper and ProjectTo working with HotChocolate so I can expose dto's to the graph and not my entire domain.  I want to do this so I can abtract away our domain and expose a very small normalized schema to our front end.  We are moving our large application to GQL and have a huge sql server schema that I'd like to gradually expose.  We use EF Core heavily but don't want to expose our entire model to GQL.

ProjectTo works as expected (queries only selected fields coming in from GQL query with UseProjection), however when I try and select a non string field 2 levels deep, then I get a "Argument types do not match".  

If I change the non-string field to a nullable field 
ex)
Change the dto's id field from
int Id 
to a nullable int
int? Id
It works, but I don't want to make all my DTO fields nullable.

**To Reproduce**
I copied the workshop and have the project setup with AutoMapper

See readme here for steps to reproduce..

https://github.com/twilly86/graphql-workshop/tree/master/code/session-9-automapper/GraphQL

Run query
```
{
  speakers{
    nodes{
      id
      sessionSpeakers{
        session{
          title
          id
        }
      }
    }
  }
}
```

Query Setup
```
 [UseApplicationDbContext]
        [UsePaging]
        [UseProjection]
        [UseSorting]
        public IQueryable<SpeakerDto> GetSpeakers(
          [ScopedService] ApplicationDbContext context,
            [Service] IMapper mapper)
        {

            var query = context.Speakers
                   .ProjectTo<SpeakerDto>(mapper.ConfigurationProvider);
 
            return query;
        }
```

**Expected behavior**

Using AutoMapper and ProjectTo with Hot Chocolage should query only selected fields with UseProjection and allow selecting of nested objects

**Additional context**
```
Error and stack strace..
"extensions": {
        "message": "Argument types do not match",
        "stackTrace": "   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryOptimizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPreprocessor.Process(Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)\r\n   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()\r\n   at HotChocolate.Types.Pagination.QueryableCursorPagingHandler`1.ExecuteQueryableAsync(IQueryable`1 queryable, Int32 offset, CancellationToken cancellationToken)\r\n   at HotChocolate.Types.Pagination.QueryableCursorPagingHandler`1.GetSelectedEdgesAsync(IQueryable`1 allEdges, Nullable`1 first, Nullable`1 last, Nullable`1 after, Nullable`1 before, CancellationToken cancellationToken)\r\n   at HotChocolate.Types.Pagination.QueryableCursorPagingHandler`1.ResolveAsync(IQueryable`1 source, CursorPagingArguments arguments, CancellationToken cancellationToken)\r\n   at HotChocolate.Types.Pagination.CursorPagingHandler.HotChocolate.Types.Pagination.IPagingHandler.SliceAsync(IResolverContext context, Object source)\r\n   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.ScopedServiceObjectFieldDescriptorExtensions.<>c__DisplayClass0_1`1.<<UseScopedService>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
```

Here is the query EF core generates when it works when returning a string field, the sub query is pretty inefficient since it queries all fields.  I would have hoped that it would only have grabbed the "title" field instead of all fields

```
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (13ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [t2].[c], [t2].[Abstract], [t2].[EndTime], [t2].[Id], [t2].[StartTime], [t2].[Title], [t2].[Id0], [t2].[Name], [t2].[TrackId], [t2].[SessionId], [t2].[SpeakerId], [t2].[c0], [t2].[EmailAddress], [t2].[FirstName], [t2].[Id1], [t2].[LastName], [t2].[UserName], [t2].[AttendeeId], [t2].[SessionId0], [t2].[SessionId1], [t2].[SpeakerId0]
FROM (
    SELECT TOP(@__p_0) [s].[Id]
    FROM [Speakers] AS [s]
) AS [t]
LEFT JOIN (
    SELECT CAST(0 AS bit) AS [c], [s1].[Abstract], [s1].[EndTime], [s1].[Id], [s1].[StartTime], [s1].[Title], [t0].[Id] AS [Id0], [t0].[Name], [s1].[TrackId], [s0].[SessionId], [s0].[SpeakerId], [t1].[c] AS [c0], [t1].[EmailAddress], [t1].[FirstName], [t1].[Id] AS [Id1], [t1].[LastName], [t1].[UserName], [t1].[AttendeeId], [t1].[SessionId] AS [SessionId0], [s3].[SessionId] AS [SessionId1], [s3].[SpeakerId] AS [SpeakerId0]
    FROM [SessionSpeaker] AS [s0]
    INNER JOIN [Sessions] AS [s1] ON [s0].[SessionId] = [s1].[Id]
    LEFT JOIN [Tracks] AS [t0] ON [s1].[TrackId] = [t0].[Id]
    LEFT JOIN (
        SELECT CAST(0 AS bit) AS [c], [a].[EmailAddress], [a].[FirstName], [a].[Id], [a].[LastName], [a].[UserName], [s2].[AttendeeId], [s2].[SessionId]
        FROM [SessionAttendee] AS [s2]
        INNER JOIN [Attendees] AS [a] ON [s2].[AttendeeId] = [a].[Id]
    ) AS [t1] ON [s1].[Id] = [t1].[SessionId]
    LEFT JOIN [SessionSpeaker] AS [s3] ON [s1].[Id] = [s3].[SessionId]
) AS [t2] ON [t].[Id] = [t2].[SpeakerId]
ORDER BY [t].[Id], [t2].[SessionId], [t2].[SpeakerId], [t2].[Id], [t2].[Id0], [t2].[SessionId0], [t2].[AttendeeId], [t2].[Id1], [t2].[SessionId1], [t2].[SpeakerId0]
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Hot Chocolate GraphQL Pipeline'
```

**Comment by nkovacic** [comment] 2021-02-15 15:13
@twilly86 ProjectTo has more arguments, where you can specify which fields should automapper expand https://docs.automapper.org/en/stable/Queryable-Extensions.html#explicit-expansion

**Comment by jannikbuschke** [comment] 2021-04-20 21:52
I also see inefficient queries on related data without AutoMapper. For me it seems UseProjections is only working on the toplevel. I.e. with following code
```csharp
[UseProjection]
public IQueryable<User> Users([Service] DataContext ctx)
{
     return ctx.User
         .Include(v => v.Author)
         .ThenInclude(v => v.Books);
}
```
the query
```graphql
users { id }
```
works fine and produces the following SQL
```sql
SELECT [u].[Id]
FROM [User] AS [u]
```
whereas the following query
```graphql
users {
  id
  author { name }
}
```
unecessary loads more data:
```sql
SELECT [u].[Id], [a].[Id], [a].[Name], [a].[UserId], [b].[Id], [b].[AuthorId], [b].[Title]
FROM [User] AS [u]
LEFT JOIN [Author] AS [a] ON [u].[Id] = [a].[UserId]
LEFT JOIN [Book] AS [b] ON [a].[Id] = [b].[AuthorId]
ORDER BY [u].[Id], [a].[Id], [b].[Id]

```

**Comment by twilly86** [comment] 2021-04-20 22:44
you shouldn't need to use includes with useprojection, do you get same
results when you remove includes?

**Comment by mrnkhlblv** [comment] 2021-06-28 17:48
Having the same kinda issue, when upgraded to ef core 5. I believe the problem is in [UseProjection], because without it works fine. Also works okay on many-to-many relationship, but not on one-to-one. As the author said, 2nd level strings, enums etc.
Workaround with nullable enums works

**Comment by ignaciojocano-ITH** [comment] 2021-08-20 20:05
I'm currently having the same issue. So the only workaround would be a nullable prop? Is there any other update?

**Comment by eduardomhg** [comment] 2021-08-23 07:54
Guys, just FYI I updated the HotChocolate Nuget packages to the latest Prerelease version (12.0.0-preview30) and this issue seems fixed in that version.

**Comment by eduardomhg** [comment] 2021-08-23 08:36
I'm also experiencing this issue, after having played with it a bit I can see the following;

1. Configuring the nested property with DoNotAllowNull in Automapper seems to be another workaround for the issue:

`CreateMap<Post, PostDto>().ForMember(p => p.Blog, opt => opt.DoNotAllowNull());`

2. Even when the ID field is not included in the query (so the error doesn't happen), the projection does not work properly in this case (1-to-1). I created a separate bug for this [here](https://github.com/ChilliCream/hotchocolate/issues/4114)
3. These issues happen with the latest v12 prerelease packages as well.

**Comment by gmavritsakis** [comment] 2021-12-13 12:04
We are also experiencing the same issue and this creates many problems to our view models.

We use many nested models mapped to the database tables and relations and because of this issue we are forced to mark most of the properties of our models nullable as most of them (the models) are nested.

This also seems to be related to [Fetching unneccsary columns when projecting to a new class #2373](https://github.com/ChilliCream/hotchocolate/issues/2373)

`CreateMap<Post, PostDto>().ForMember(p => p.Blog, opt => opt.DoNotAllowNull());`

does not work for us.

**Comment by PascalSenn** [comment] 2021-12-14 23:53
Can you try once #4563 is merged if it works with the new extension method?
1. `dotnet add package HotChocolate.Data.AutoMapper`
2.  Rewrite the mapping to:
```csharp
        [UseProjection]
        public IQueryable<PostDto> GetPosts(BloggingContext dbContext, IResolverContext context)
            => dbContext.Posts.ProjectTo<Post, PostDto>(context);
```

**Comment by gmavritsakis** [comment] 2021-12-19 09:20
Hi @PascalSenn .
It seems merging for this issue is halted.

**Closed** 2021-12-21 22:40 UTC
Labels: ❓ question, 🌶️ hot chocolate

**Comment by gmavritsakis** [comment] 2022-02-12 23:43
Hi @PascalSenn 
Unfortunately this seems to not be working.
I still have the same problems even by using the new extension.

**Comment by eduardomhg** [comment] 2022-02-14 07:54
I've also tested this with the new version and also seen the same issue. 

My current workaround is still to make all DTO property types nullable.

**Comment by eduardomhg** [comment] 2022-03-02 17:12
@gmavritsakis I've now tested with HotChocolate.Data.Automapper 12.6.1 and Automapper 10.1 and I can't see the issue anymore, not sure if I'm missing something. 

Can you confirm it this is fixed for you as well?

**Comment by gmavritsakis** [comment] 2022-03-16 11:43
@eduardomhg we have finally managed to make it work!

We had to do all the needed steps for this to work:

1. Automapper exact version 10.1.1 no more, no less
2. AutoMapper extensions 8.1.1 (for DI)
3. Append for all models in profiles the `.ForAllMembers(opt => opt.ExplicitExpansion());`
4. Update HotChocolate to latest version (v12.7)

Obviously the use of past AutoMapper version for this to work is not preferable, but we hope AutoMapper team will catch up in future versions.

In any case many thanks to @PascalSenn

**Comment by RawMajkel** [comment] 2022-04-24 17:23
Hi,
[UseProjection] with mapping to DTO objects doesn't seem to work properly - it causes overfetching data.

I am using latest versions of AutoMapper and HotChocolate (11.0.1 and 12.8.0)

```
[UseProjection]
public IQueryable<WeatherDto> GetWeather([Service] IWeatherRepository weatherRepository, IResolverContext context)
    => weatherRepository
        .GetAsQueryable() // returns context.Weather
        .ProjectTo<Weather, WeatherDto>(context);
```

```
CreateMap<Weather, WeatherDto>() // tried CreateProjection too
    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id.Value));
```

Querying for any weather data:

```
query {
  weather {
    id
  }
}
```

...results with selecting all entity from database and then truncating it to dto.

```
Executed DbCommand (46ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT w."Id", w."Date", w."TemperatureC", w."TemperatureF", w."Summary"
FROM "Weather" AS w
```

Any way I could get this to work properly?
Not mapping - projection works as expected.
