### ISSUE TITLE
non-nullable field with authorize directive will make the result object type null (instead of only the field)

### ISSUE THREAD

**Issue by nollidnosnhoj** [ChilliCream/hotchocolate#4838] opened 2022-03-12 03:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

sample: https://github.com/nollidnosnhoj/test

Hello. I came across a (possibly intentional) bug with the authorize directive. When you use the authorize directive on a field definition that is nullable, and the user is not authorized, the expected (and actual) behavior is that the field will become null.

However, if you apply the directive to a field that is non-nullable. The whole object type where the field belongs to become null, instead of the field itself.

### Steps to reproduce

1. Clone the provided repository
2. Build and run the repository
3. In BananaCakePop, run this query below. This is the expected since secret is nullable.
```
query {
  tests(count: 2) {
    items {
      id
      name
      secret
    }
  }
}
```
4. Then run the query below. Since secretNumber is not nullable, the items field becomes null, when the field with the directive should at least give a default value (0).
```
query {
  tests(count: 2) {
    items {
      id
      name
      secret
      secretNumber
    }
  }
}
```

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "tests",
        "items",
        1,
        "secretNumber"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    },
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "tests",
        "items",
        1,
        "secret"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    },
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "tests",
        "items",
        0,
        "secretNumber"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    },
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "tests",
        "items",
        0,
        "secret"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    }
  ],
  "data": {
    "tests": {
      "items": null
    }
  }
}
```

### Additional Context?

My (probably wrong) theory is that since the field is non-nullable, the directive gets confused (?). The directive works for nullabe field definition, but not non-nullable fields. I am probably missing something, so feel free to tell me! Thank you so much!

### Product

Hot Chocolate

### Version

12.7.0

**Comment by tobias-tengler** [comment] 2022-03-12 05:09
This is the expected behavior, when the field raises an error and it can not be null, the null propagates to the nearest nullable parent field. [Reference](https://spec.graphql.org/October2021/#sec-Executing-Selection-Sets.Errors-and-Non-Null-Fields)

You can either make the field nullable or use the client-controlled nullability feature to specify that you are fine with this non-null field returning null:

```graphql
query {
  tests(count: 2) {
    items {
      id
      name
      secret
      secretNumber?
    }
  }
}
```

Just a heads up: The client-controlled nullability feature is still [experimental and not yet merged into the spec](https://github.com/graphql/graphql-spec/pull/895).

Closing this, since what's happening is the expected behavior.

**Closed** 2022-03-12 05:10 UTC
Labels: 🐛 bug
