### ISSUE TITLE
Subscription is not working in MapGraphql Extension while using with RequireAuthorization

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/hotchocolate#3003] opened 2021-02-06 09:03 UTC
Hi,
Using RequireAuthorization() in MapGraphql() results in Subscription call failure with error "Could not connect to websocket endpoint ". Without RequireAuthorization, its just working fine as expected. Should anything need to be added as service to make it as work?

    app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapGraphQL();
                endpoints.MapGraphQL("/web", schemaName: "web").RequireAuthorization();

                endpoints.MapGet("/", context =>
                {
                    context.Response.Redirect("/playground");
                    return Task.CompletedTask;
                });
            });
  app.UsePlayground("/web", "/playground");

**Comment by user321-creator** [comment] 2021-02-16 12:35
@michaelstaib  any update ?

**Comment by user321-creator** [comment] 2021-02-18 08:15
@michaelstaib 
 
We are trying to load schema only if the Authorization Header is valid.If the Authorization token is not valid.,it should'nt load schema. To implement this case, I m using RequireAuthorization in MapGraphql Extension and its working fine as expected for Queries and Mutations.But when it comes to subscription.,it results in subscription failure with error "Could not connect to websocket endpoint".

Expected Behaviour :
Subscription should start listening to the topic.

Startup : [Startup.txt](https://github.com/ChilliCream/hotchocolate/files/6001175/Startup.txt)

**Comment by user321-creator** [comment] 2021-02-24 08:25
@PascalSenn  @michaelstaib  any update reg-this issue..or do u need any other input from my side?

**Comment by PascalSenn** [comment] 2021-02-25 08:26
How do you do the authentication then?
You cannot authenticate over headers on subscriptions, you either need to use s url get parameter or you use the first messsge to send rhe payload

https://gist.github.com/PascalSenn/43fedfbc1bc96692d99263a9da2d9ac4

this is for v10, for v11 you may need some other classes for the interceptor bit it should still work

**Comment by RehanSaeed** [comment] 2021-03-29 12:01
This seems like a duplicate of https://github.com/ChilliCream/hotchocolate/issues/3119.

**Comment by PascalSenn** [comment] 2022-03-14 12:35
Closed in favour of #3119

**Closed by PascalSenn** 2022-03-14 12:35 UTC
Labels: ❓ question, 🌶️ hot chocolate, Area: Subscriptions
