### ISSUE TITLE
Timestamps without offset information are incorrectly treated as being in server time and translated to UTC

### ISSUE THREAD

**Issue by Zero3** [ChilliCream/hotchocolate#2604] opened 2020-11-18 13:10 UTC
In one of my code-first input models, I have a field that takes a future local timestamp in an elsewhere specified time zone. It looks like this:

````
public DateTime LocalDateAndTimeInFuture { get; set; }
````

When querying, I provide a timestamp *without offset* like this:

````
localDateAndTimeInFuture: "2020-11-21T00:00:00"
````

But when HotChocolate is executing the query, the actual value of my `LocalDateAndTimeInFuture` field is `20-11-2020 23:00:00` with `DateTimeKind.Utc`! It should have contained the same value as the input timestamp, with `DateTimeKind.Unspecified` (or maybe `DateTimeKind.Local`).

So what went wrong? I've identified two pieces of code in HotChocolate which cause this issue:

In `DateTimeType.cs`, timestamps without trailing `Z` are mishandled by parsing them into a `DateTimeOffset`:

````
            if (DateTimeOffset.TryParse(
                serialized,
                out DateTimeOffset dateTime))
            {
                obj = dateTime;
                return true;
            }
````

In `TypeConversion.Setup.cs`, the `DateTimeOffset` is translated into a `DateTime` with `DateTimeKind.Utc`:

````
            registry.Register<DateTimeOffset, DateTime>(
                from => from.UtcDateTime);
````
There are multiple issues with this:

* The code assumes that the timestamp is in the UTC offset of the time zone of the server (+1 in this case), which is incorrect.
* The code binds the timestamp to an UTC offset, which is incorrect (the UTC offset of a future local timestamp can be changed by legislation etc.)
* The code changes the local timestamp to an UTC timestamp, which is incorrect.

HotChocolate version: 10.5.3

**Comment by michaelstaib** [comment] 2020-11-19 07:38
https://www.graphql-scalars.com/date-time/

I think the GraphQL scalar should actually throw if no offset is specified since it was envisioned to always carry an offset.

Internally we only use `DateTimeOffset` the way it converts to `DateTime` can be changed.

This is how version 11 is handling it:

```csharp
    private static bool TryDeserializeFromString(
            string? serialized,
            [NotNullWhen(true)]out DateTimeOffset? value)
        {
            // if we find a z offset we will use utc 2011-08-30T13:22:53.108Z
            if (serialized is not null
                && serialized.EndsWith("Z")
                && DateTime.TryParse(
                    serialized,
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal,
                    out DateTime zuluTime))
            {
                value = new DateTimeOffset(
                    zuluTime.ToUniversalTime(),
                    TimeSpan.Zero);
                return true;
            }

            // if an offset exists we will parse it with DateTimeOffset
            if (serialized is not null
                && DateTimeOffset.TryParse(
                    serialized,
                    out DateTimeOffset dt))
            {
                value = dt;
                return true;
            }

            // no offset exists, we will not parse it.
            value = null;
            return false;
        }
```

Have a look at the test cases defined in the spec.

**Comment by Zero3** [comment] 2020-11-21 14:23
@michaelstaib Thanks for replying.

> I think the GraphQL scalar should actually throw if no offset is specified since it was envisioned to always carry an offset.

But then how can one have a datetime field for a local datetime without a specific UTC offset? This is needed for various use cases, like representing events in future local time. In these cases, UTC datetimes and datetimes with UTC offsets are not appropriate, because the UTC offset might change before the event occurs (e.g. changes to daylight saving time, new UTC offset for the country, ...). So to avoid sending such datetimes in inappropriate formats and working around it on both the client and the server, one really need to be able to send a truly local time, independent of UTC. Something like `LocalDateTime` from NodaTime (see https://nodatime.org/3.0.x/userguide/type-choices).

**Comment by tobiasr** [comment] 2021-03-10 20:35
I also spent some major time on finding and understanding parts of this issue.

I'm using PostgreSQL under EF Core and the "recommended" solution for timestamps are to be saved as `DateTime` properties (in `timestamp without time zone` columns). When a `DateTime` is read back from the database it will have Kind=Unspecified (https://www.npgsql.org/doc/types/datetime.html). `DateTimeOffset` (in `timestamp with time zone` column) seems to not be recommended, this might be different from SQL Server.

There is no way for me to have PostgreSQL (and Npqsql) return a DateTime represented as Kind=UTC even if it is saved as UTC.

HotChocolate then adds the local server time offset to the DateTime in the process of the conversion to DateTimeOffset (because Kind=Unspecified) which makes the returned DateTime one offset off. For example:

Stored in database: 2021-03-10 15:37:29.683113
Returned from HotChocolate GraphQL: 2021-03-10T15:37:29.683+01:00 (server time offset -> which then indicates that the UTC time is one hour earlier than it actually is)

I think the solution here would be to be able to tell HotChocolate not to change the date from the DB in any way, somehow?

My current solution is to add a `ValueConverter` for `DateTime` properties in `OnModelCreating` that sets the Kind=DateTimeKind.Utc as described here: https://stackoverflow.com/a/50728577/97598. But this doesn't feel like the correct solution.

**Comment by Zero3** [comment] 2022-05-08 19:09
Well... If my issues get automatically closed by stalebot like this, I will most likely stop contributing bug reports to this project. I already spent time creating the bug reports, so seeing it wasted by having them closed by a bot because they have not been fixed yet is super demotivating.

**Comment by plucasr** [comment] 2022-07-16 00:55
I'm integrating a schema stitching with a schema from Hasura, the database there has timestampz fields being used as timestampz so I can't change them, does someone knows how could I override it or convert it?

The error: 
`Unable to resolve type reference None: timestamptz!. `

**Comment by michaelstaib** [comment] 2022-07-21 21:22
The solution here in your case is to enrich the DateTime with extra information. Internally we use DateTimeOffset. You can override the type converter to specify that your DateTimes are converted with the offset that you need for your usecase.

```csharp
services
    .AddGraphQLServer()
    .AddTypeConverter<DateTime, DateTimeOffset>(dateTime => Do your own conversion here);
```

**Comment by michaelstaib** [comment] 2022-07-21 21:27
Closing this issue since the scalar is correctly implemented and the issue for your use-case is the default conversion that we have registered.

This is the default setup:

```csharp
        registry.Register<DateTimeOffset, DateTime>(from => from.UtcDateTime);
        registry.Register<DateTime, DateTimeOffset>(from => from);
```

**Closed by michaelstaib** 2022-07-21 21:27 UTC
Labels: ❓ question, 🌶️ hot chocolate

**Comment by SimonGates** [comment] 2022-07-25 08:47
@michaelstaib I'm using SQL Server and using datetime2 throughout my Schema storing UTC values, no requirement for timezone offset information and none is stored in the columns datetime2 doesn't include this information. I experience the same behaviour as @tobiasr for simple queries

> Stored in database: 2021-03-10 15:37:29.683113
> Returned from HotChocolate GraphQL: 2021-03-10T15:37:29.683+01:00 (server time offset -> which then indicates that the UTC time is one hour earlier than it actually is)

Personally, especially looking at this from a data reading & querying perspective, I think this is a bug. I think it's wrong that HotChocolate treats timestamps without offsets in this way. If there is no offset in the timestamp stored in the DB, HotChocolate shouldn't add one by using the local machine timezone which often differs between developer machines and deployment environments anyway, it's likely this doesn't give consistent results and probably leads to bugs when releasing to environments. HotChocolate should set the offset to +00:00 unless explicitly overridden by the developer using the API HotChocolate provides. Unless of course, the timestamp includes it.

For now I'll have to use @tobiasr solution on StackOverflow unless there is an alternative?

**Comment by michaelstaib** [comment] 2022-07-25 10:15
@SimonGates Hot Chocolate implements the spec for DateTimeType in GraphQL which always demands an offset. We actually only deal with `DateTimeOffset` internally.

So, if you want consistent behavior in your project then implementing the converters as specified above is a very clean solution.

We also have people arguing the other side. We have insurance companies where the time stored in the DB is always local time as all contract that are signed are signed by are in the local context. So all dates selected from the database without an offset are by default local.

For me this is an implementation detail. We implemented the default converters as I explained. What we cannot do is change them since that would break everyone.

Especially with DateTime its difficult to find consensus. But I really do not see your issue here since you can change the default behavior how we handle the conversion.

It is not a bug. It is designed this way for the requests of users we had at one point. But, we will find a documentation section to make this more clear and tell people that they should declare this for their use-case.
