### ISSUE TITLE
StrawberryShake using a value-type as a parameter produces invalid code

### ISSUE THREAD

**Issue by Alxandr** [ChilliCream/hotchocolate#3986] opened 2021-07-23 12:14 UTC
**Describe the bug**
If you have a value-type as a custom-scalar `@runtimeType`, and use that as a query parameter, invalid code is produced.

**To Reproduce**

Schema:

```gql
schema {
  query: Query
}

type Query {
  foo(v: Foo!): String!
}

scalar Foo
```

Schema extensions:

```gql
extend scalar Foo
  @serializationType(name: "global::System.String")
  @runtimeType(name: "global::Test.Foo", valueType: true)
```

Query:

```gql
query test($foo: Foo!) {
  foo(v: $foo)
}
```

Generated code:

```csharp
        private global::System.Object? FormatFoo(global::Test.Foo value)
        {
            if (value is null) // <-- Error	CS0037	Cannot convert null to 'Foo' because it is a non-nullable value type
            {
                throw new global::System.ArgumentNullException(nameof(value));
            }

            return _fooFormatter.Format(value);
        }
```

**Expected behavior**
The generated code should compile.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by brian-tygotech** [comment] 2021-12-24 15:19
This looks like a duplicate of #3678.

**Closed** 2021-12-25 21:10 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
