### ISSUE TITLE
very large numbers not supported by Float input types

### ISSUE THREAD

**Issue by freever** [ChilliCream/hotchocolate#1978] opened 2020-05-23 11:28 UTC
I am trying to use HC with CF to maintain data about star systems, including the mass of the star - which I would like to be measured in units of kg. I have an InputType defined for the mutation to create a star with a field for MassKg using a <NonNullType<FloatType>>. From what I understand, the Float type in GraphQl should support the same range of values as the C# double, so I expect values that work in my C# code to flow across the GraphQL API without any issues. However I am receiving a 400 Bad Request response from my HC server once the size of this number passes a threshold. 

For instance, The mass of our sun is 1.989e+30, but this returns Bad Request. 1.989e+29 also fails. But 1.989e+28 gets through. 

Oddly, if I hack a workaround to allow the big numbers to get through the mutation in reduced form and then upsize them on the server, then once the star is created with a MassKg of 1.989e+30 I am able to download that property through my HC API without any issues. So the problem seems to be confined to the InputType. 

I am using HC for AspNetCore v11 preview 127.

**Comment by michaelstaib** [comment] 2020-05-23 22:01
Could you write a test case for the `FloatType`? I can point you to the right test file.

**Comment by freever** [comment] 2020-05-24 05:14
Yes please. I would like to know the source better and this would be a good
place to start.

**Comment by freever** [comment] 2020-05-28 07:09
@michaelstaib just a reminder to let me know where to find the tests for this and I will try to replicate the issue

**Comment by michaelstaib** [comment] 2020-05-28 07:20
Sorry for the wait. 

I would start with the standard scalar tests:
https://github.com/ChilliCream/hotchocolate/blob/master/src/HotChocolate/Core/test/Types.Tests/Types/Scalars/FloatTypeTests.cs

If the issue is not there we can have a look at the parsers.

**Comment by freever** [comment] 2020-05-28 07:32
Hmm, no luck there. Perhaps I am doing something wrong. I will try and create a simple reproduction project on my end and work from there.

**Comment by michaelstaib** [comment] 2020-09-16 09:41
This one is now fixed with the 11.0.0-dev.12

**Closed** 2020-09-16 09:42 UTC
Labels: 🌶 hot chocolate, 🔍 investigate
