### ISSUE TITLE
The specified directive `include` is not supported by the current schema.

### ISSUE THREAD

**Issue by RaYell** [ChilliCream/hotchocolate#1470] opened 2020-02-12 09:22 UTC
I want to use the include directive and according to the [docs](https://hotchocolate.io/docs/directives) it should work out-of-the-box:

> GraphQL specifies three directives in the spec (skip, include and deprecated) which are always registered with your schema.

However in my case when I run my query

```
query MyQuery($tenantId: Uuid!, $withContractNo: Boolean! = true) {
  contracts(tenantId: $tenantId) {
    nodes {
      contractNo @include(if: $withContractNo)
    }
  }
}
```

Variables are also defined correctly:
```
{
  "tenantId": "2B05987E-F9B4-4348-BCE0-712D90C48B24"
  "withContractNo": true
}
```

I'm getting this error message:
```
{
  "errors": [
    {
      "message": "The specified directive `include` is not supported by the current schema.",
      "locations": [
        {
          "line": 4,
          "column": 18
        }
      ]
    }
  ]
}
```
I've even tried registering if manually during app startup
```
SchemaBuilder.New()
    .AddServices(sp)
    .AddQueryType<QueryType>()
    .AddDirectiveType<IncludeDirectiveType>()
    .ModifyOptions(x => x.RemoveUnreachableTypes = true)
    .Create().
```
But even that makes no difference. Is it possible that the documentation for directives is outdated or am I missing something in my app?

I'm using v10.3.5.

**Comment by michaelstaib** [comment] 2020-02-18 19:01
I could not reproduce this so far. Can you provide us with a repro?

**Comment by RaYell** [comment] 2020-02-19 12:45
I think I found where the problem is. In my Startup I had 
`.ModifyOptions(x => x.RemoveUnreachableTypes = true)`

If I remove this line then `@include` directive is working as expected.

**Comment by michaelstaib** [comment] 2020-02-19 12:58
Ah, but that is a bug. This should not remove directives. I will look into that.

**Comment by chlumper** [comment] 2020-07-17 08:58
Hi!
I had the same issue with the `.AddExportDirectiveType()` resulting in  
`The specified directive `export` is not supported by the current schema.`
if I use  `.ModifyOptions(x => x.RemoveUnreachableTypes = true)` on `10.4.3`.

With `.ModifyOptions(x => x.RemoveUnreachableTypes = false)` everything works as expected.

**Comment by michaelstaib** [comment] 2020-11-18 14:28
this one is now fixed.

**Comment by michaelstaib** [comment] 2020-11-18 14:48
With the new configuration API we have added a shortcut to enable type trimming:

```csharp
new ServiceCollection()
    .AddGraphQL()
    ...
    .TrimTypes()
```

**Closed** 2020-11-18 15:09 UTC
Labels: :beetle: bug, 🌶 hot chocolate
