### ISSUE TITLE
BCP hides directives in "Schema Definition" view

### ISSUE THREAD

**Issue by doeringp** [ChilliCream/hotchocolate#4758] opened 2022-02-14 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using the `AuthorizeAttribute` of HotChocolate to apply authorization rules on methods:

```csharp
[ExtendObjectType(OperationTypeNames.Query)]
public class UserQueries
{
    [Authorize(Policy = "RequireUser")]
    public Task<User?> GetMeAsync(IResolverContext context, [Service] UserRepository repository)
    {
      // ...
    }
}
```

The policy-based authorization works well, but the schema definition in BCP lacks the `@authorize` directive on the `me` field. The directive is declared as type, but I cannot find it on the field.

![image](https://user-images.githubusercontent.com/20394732/153870252-cd9a3821-a822-45d0-b380-cf1b020bdd4e.png)

When I download the schema definition via `/graphql?sdl` the `@authorize` directive is there:
```graphql
type Query {
  me: User @authorize(policy: "RequireUser", apply: BEFORE_RESOLVER)
}
```
For me, it looks like BCP suppresses all directives, also other directives than `@authorize`.

### Steps to reproduce

1. 

### Additional Context?

I'm using ASP.NET Core 6.0

### Product

Hot Chocolate

### Version

12.6.0

**Comment by michaelstaib** [comment] 2022-02-15 09:35
That is not a BCP issue. BCP uses introspection to discover types. From the introspection result, we are then creating the SDL. The introspection as of now does not provide any info about type system directives. Hot Chocolate could provide the SDL but other GraphQL servers do not have this capability.

For future versions of BCP, we want to allow the user to specify an SDL endpoint that would allow this.

The SDL can be downloaded from HotChocolate via the following URL:
http://localhost/graphql?sdl

Beware that we changed the authorize directive in newer versions to not appear in the SDL anymore as to not expose the internal auth directives to the public.

I am closing this issue since this is not a bug.

**Closed by michaelstaib** 2022-02-15 09:35 UTC
Labels: ❓ question, 🌶️ banana cake pop
