### ISSUE TITLE
UploadType is not working in Schema Stitching

### ISSUE THREAD

**Issue by Archuna** [ChilliCream/hotchocolate#3954] opened 2021-07-15 09:07 UTC
My micro server has the following Graphql schema with upload type being added as Scalar and it has no problem at all, working fine as a separate server.

type Mutation{ me(info:Upload!):String! }

 I am trying to stitch schema of base server to another Federation server.  while stitching( i.e while loading the federated server schema in playground) I m getting the error saying " **Unable to resolve dependencies Input: Upload! for type `Mutation`**. (HotChocolate.Types.ObjectTypeExtension)" eventhough UploadType is added in federataion server like AddType< UploadType >().

If my base server schema has StringType instead of UploadType like below.,Schema stitching is working without throwing any error,seems like UploadType is problem.

There was similar issue with AnyType as well and seems to be fixed in latest versions.

**Comment by PascalSenn** [comment] 2021-07-15 14:10
Closing as a dupe of #3760

**Closed by PascalSenn** 2021-07-15 14:10 UTC
Labels: 🎉 enhancement, 🐛 bug, 🐾 duplicate
