### ISSUE TITLE
How do you efficiently debug "One of the identified items was in an invalid format" ?

### ISSUE THREAD

**Issue by jeancallisti** [ChilliCream/hotchocolate#3455] opened 2021-04-08 15:50 UTC
Error "One of the identified items was in an invalid format" seems to be the error I get the most frequently.
It's usually caused by me making a mistake in the schema : null field, or wrong type, or whatnot.

Yet sometimes it takes me a tremendous amount of time to find what field is responsible.
Worse: Very few people seem to have the same issue as I do -- This error pops up only a handful of times in Google, for obscure, very specific issues that seldom have the same root cause as mine.

Hence my question : Is there a way to display with **what field** strawberryshake is encountering issues, and why?

**Comment by michaelstaib** [comment] 2021-04-09 06:23
With the June release we will have a better error message that exactly tells you what is wrong.

**Comment by jeancallisti** [comment] 2021-04-09 07:41
More generally, is there a way to display more info (any info at all) on either end of the flow (encoding on server side or decoding on client side)

**Comment by michaelstaib** [comment] 2021-04-11 11:54
Not really, but we will redesign this and will add diagnostic events.

**Comment by PascalSenn** [comment] 2021-04-14 17:46
Duplicate of #3111

**Comment by michaelstaib** [comment] 2021-06-27 19:46
Closing this since it is a duplicate. We will soon release a preview with a for #3111

**Closed by michaelstaib** 2021-06-27 19:46 UTC
Labels: 🌶️ hot chocolate, 🐛 bug, 🐾 duplicate
