### ISSUE TITLE
Invalid Uuid is still validated when using `.AddType(new UuidType('D'))`

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#4235] opened 2021-09-15 11:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When HC server is configured with `.AddType(new UuidType('D'))`, it seems to accept uuids that are in fact invalid. 

Specifically, if you append something to a valid uuid, HC seems to simply ignore the excess and proceed as if everything is fine.

### Steps to reproduce

1. Checkout https://github.com/hognevevle/HC-uuid-bug
2. `dotnet run`
3. Run curl:

```
curl 'http://localhost:5000/graphql/' \
  -H 'Referer: ' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw '{"operationName":"foo","query":"query foo {\n  foo(id: \"fbdef721-93c5-4267-8f92-ca27b60aa51f-foobar\")\n}\n","variables":{}}' \
  --compressed
```

Notice the appended `-foobar` at the end of the `id` variable, which makes the uuid invalid. Still, the server returns a valid response:

`{"data":{"foo":"Hey fbdef721-93c5-4267-8f92-ca27b60aa51f"}}`

So it basically seems to just strip away whatever is invalid.

### Additional Context?

By commenting `.AddType(new UuidType('D'))` in `Startup.cs`, the uuid is validated as expected (does not accept the invalid uuid).

### Product

Hot Chocolate

### Version

11.3.7

**Comment by michaelstaib** [comment] 2021-09-16 21:25
`public UuidType(char defaultFormat = '\0', bool enforceFormat = false)`

by default we do not enforce the format on deserialization. you can pass enforceFormat = true along and it will start throwing.

**Comment by hognevevle** [comment] 2021-09-17 07:40
@michaelstaib  Already tried that, but setting that to true doesn't make a difference.

![CleanShot 2021-09-17 at 09 40 05](https://user-images.githubusercontent.com/2721188/133744118-14fb7967-dfbe-4f52-a00d-d3a1d2685578.png)

**Comment by hognevevle** [comment] 2021-09-17 07:44
However, even if you're not forcing the format on deserialization, I would still expect you should have to provide a _valid_ Uuid (as long as it has a valid _format_)?

**Comment by hognevevle** [comment] 2021-09-21 09:26
Please reopen :)

**Comment by michaelstaib** [comment] 2021-09-24 06:41
I can reproduce this issue.

It actually comes down to the `Utf8Formatter` from .NET

```csharp
if (Utf8Parser.TryParse(valueSyntax.AsSpan(), out Guid g, out _, _format[0]))
{
    return g;
}
```

while this is a TryParse method it will just slice the data to the expected length.

**Comment by michaelstaib** [comment] 2021-09-24 07:03
The issue is now fixed and under test.

**Comment by michaelstaib** [comment] 2021-09-24 07:03
We will release it with the next rc build.

**Comment by michaelstaib** [comment] 2021-09-24 07:04
By the way, this indeed has nothing todo with enforce format. Enforce format will only enforce if something is deviating form the default format.

**Comment by hognevevle** [comment] 2021-09-24 08:04
Awesome, thank you very much for confirming and fixing 🥳

**Closed** 2021-09-24 08:48 UTC
Labels: 🐛 bug, 🌶️ hot chocolate

**Comment by michaelstaib** [comment] 2021-09-24 09:11
https://github.com/ChilliCream/hotchocolate/releases/tag/11.3.8

**Comment by michaelstaib** [comment] 2021-09-24 09:12
we also created a patch release which should hit nuget in the next hour.
