### ISSUE TITLE
HotChocolate Subscription + UseFiltering publishes nulls

### ISSUE THREAD

**Issue by benbierens** [ChilliCream/hotchocolate#4825] opened 2022-03-09 07:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're using the [UseProjection], [UseFiltering] and [UseSingleOrDefault] middlewares to allow clients to subscribe to notifications by ID.

<img width="656" alt="HT_subscription_code" src="https://user-images.githubusercontent.com/39762930/157391372-9f98b8cf-066b-49b3-a0cf-e5538d10aff7.png">

Current behavior: When a TopicEvent is sent, all subscriptions for IDs that do NOT match will be triggered, receiving a null object.

<img width="1020" alt="HT_subscription_triggered" src="https://user-images.githubusercontent.com/39762930/157390750-ad5f74f1-58b3-4fda-8626-83717bbd9270.png">

Expected behavior: When a TopicEvent is sent, all subscriptions for IDs that do NOT match are not triggered.

### Steps to reproduce

1. Set up a HotChocolate endpoint with subscriptions.
2. Apply the UseProjection, UseFiltering, and UseSingleOrDefault attributes.
3. Use Banana Cake Pop (or other client) to subscribe to a topic, applying a filter.
4. Trigger the subscription topic with an entity that does not pass the applied filter.
5. (Unexpected behavior) Subscription topic is triggered, null object is received.
Expected behavior: Subscription topic is not triggered.

### Product

Hot Chocolate

### Version

12.6.2

**Comment by michaelstaib** [comment] 2022-03-09 17:22
Filtering will not work in this way. We can have a look at throwing an exception if filtering is applied on a root field of subscription.

**Comment by michaelstaib** [comment] 2022-03-09 17:23
Closing this issue since it does not work this way by design.

**Comment by michaelstaib** [comment] 2022-03-09 17:36
You could however create something like this on your own by handling the stream yourself.

**Closed** 2022-03-09 17:39 UTC
Labels: ❓ question, 🌶️ hot chocolate, Area: Subscriptions
