### ISSUE TITLE
Encapsulated collections with backing fields. Bug or feature?

### ISSUE THREAD

**Issue by MaximS** [ChilliCream/hotchocolate#4635] opened 2022-01-11 20:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Query result does not include navigation property for encapsulated collection with backing field.
I'm not sure if it's a bug or a feature...

### Steps to reproduce

1. Model:
```
public class Phone
    public int Id { get; set; }
 ....
    private List<PhoneState> _states = new List<PhoneState>();
    public virtual IReadOnlyCollection<PhoneState> States => _states;
```
[UseProjection] is on:
```
    public class Query
    {
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        [UseOffsetPaging()]
        public IQueryable<Phone> GetPhones(PhonesContext context) => context.Phones;
        ...
    }
```

2. Query:
```
query {
  phones {
    id
    items {
      states {
        since
        value
      }
    }
  }
}
```
3. Result does not include `states`. ("states": null)
4. If replaced with 
```
public virtual ICollection<PhoneState> States { get; set; } = new List<PhoneState>();
```
everything works fine.
In this "happy" case the following expression is build (console):
```
      DbSet<Phone>()
          .Select(_s1 => new Phone{ 
              Id = _s1.Id, 
              States = _s1.States
                  .Select(p1 => new PhoneState{ 
                      Since = p1.Since, 
                      Value = p1.Value 
                  }
                  )
          }
          )
```

But in case of encapsulated collection with backing field the expression is just:
```
      DbSet<Phone>()
          .Select(_s1 => new Phone{ 
              Id = _s1.Id
          }
          )
```

Another "workaround" is to disable [UseProjection] and add `Include(p => p.States)`
```
        [UseFiltering]
        [UseSorting]
        [UseOffsetPaging()]
        public IQueryable<Phone> GetPhones(PhonesContext context) => context.Phones.Include(p => p.States);
```
But this "workaround" is not appropriate because it forces to load `states` even when they are not needed.

If it's a feature it should be documented.
But it would be better to be a bug that can be fixed.

### Additional Context?

.NET Core 6.0

```
builder.Services
    .AddGraphQLServer()
        .AddAuthorization()
        .AllowIntrospection(true)
        .AddQueryType<Query>()
        .RegisterDbContext<PhonesContext>(DbContextKind.Synchronized)
        .AddFiltering()
        .AddSorting()
        .AddProjections()
        .AddMutationConventions();
```

No `UseLazyLoadingProxies()`

### Product

Hot Chocolate

### Version

12.4.0

**Comment by tobias-tengler** [comment] 2022-01-11 20:26
I would assume the issue is the lack of a public setter in the not working example. `Property => _backingValue` is a get only property. The requirement for a public setter is mentioned in the beginning of the projections documentation.

Try changing it to

```csharp
private List<PhoneState> _states = new List<PhoneState>(); 

public virtual IReadOnlyCollection<PhoneState> States { get; set; } = _states;
```

I'm closing this for now, but feel free to reopen, if this does not address your issue.

**Closed** 2022-01-11 20:27 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data
