### ISSUE TITLE
HotChocolate 10.4.0 Not Working with CORS

### ISSUE THREAD

**Issue by Keith3679** [ChilliCream/hotchocolate#1700] opened 2020-04-14 10:47 UTC
**Describe the bug**

I have implemented HotChocolate in my .NET Core 3.0 Web API along with my existing Controllers.  I have a CORS Default Policy which is working great with the existing Controllers. When I make GraphQL Queries, Mutations, and Subscriptions via Banana Cake Pop or Postman, everything works as expected.  However, when I make GraphQL calls using Apollo in my React client, I see that the query gets called but the server is not responding back with the Access-Control-Allow-Origin headers and thus satisfying CORS on the client.  Instead I get the following error in the Client Console "**Access to fetch at 'http://localhost:5000/graphql' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**" and "**POST http://localhost:5000/graphql net::ERR_FAILED**"

**Startup.cs**

`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDirectoryBrowser();

            // Data Layers
            string dataPath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "LAMP");

            var jnlDirectory = Environment.GetEnvironmentVariable("JNLDIRECTORY") ?? System.IO.Path.Combine(dataPath, "Jnls");
            services.AddSingleton<IJnlDataLayer>(new JnlFileSystem(jnlDirectory));

            var lampEventDirectory = Environment.GetEnvironmentVariable("LAMPEVENTDIRECTORY") ?? System.IO.Path.Combine(dataPath, "Events");
            services.AddSingleton<ILAMPEventDataLayer>(new LAMPEventFileSystem(lampEventDirectory));

            // API Services
            services.AddSingleton<IJnlService, JnlService>();
            services.AddSingleton<IPlatformService, PlatformService>();
            services.AddSingleton<IDesignOptionService, DesignOptionService>();
            services.AddSingleton<ILAMPEventService, LAMPEventService>();

            services.AddSwaggerGen(c => { c.SwaggerDoc("v1", new OpenApiInfo { Title = "LAMP API", Version = "V1" }); });

            // GraphQL Services
            services.AddInMemorySubscriptionProvider();

            services.AddGraphQL(sp => SchemaBuilder.New()
                .AddServices(sp)
                .AddQueryType(d => d.Name("Query"))
                .AddMutationType(d => d.Name("Mutation"))
                .AddSubscriptionType(d => d.Name("Subscription"))
                .AddType<Query>()
                .AddType<Mutation>()
                .AddType<Subscription>()
                .Create());

            // CORS
            var cors = Environment.GetEnvironmentVariable("CORS");
            var origins = cors?.Split(',', StringSplitOptions.RemoveEmptyEntries);

            if (origins == null || origins.Length == 0)
            {
                origins = new string[] { "http://localhost", "http://localhost:3001" };
            }

            services.AddCors(options =>
            {
                options.AddDefaultPolicy(
                builder =>
                {
                    builder.WithOrigins(origins)
                           .AllowAnyHeader()
                           .AllowAnyMethod();
                });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMiddleware<ExceptionMiddleware>();

            app.UseDefaultFiles(new DefaultFilesOptions
            {
                DefaultFileNames = new List<string> { "index.html" }
            });

            app.UseStaticFiles();

            app.UseRouting();

            app.UseWebSockets();

            app.UseGraphQL("/graphql");

            app.UseCors();

            app.UseAuthorization();

            app.UseSwagger();

            app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/v1/swagger.json", "LAMP API V1"); });

            app.UseSerilogRequestLogging();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }`

**Test Query**

`using HotChocolate.Types;

namespace LAMP.GraphQL
{
    [ExtendObjectType(Name = "Query")]

    public class Query
    {
        public string Hello => "World";

        public int GetPlatform(int id)
        {
            return id;
        }

        public Platform GetPlatforms()
        {
            Platform platfrom = new Platform();

            platfrom.Jnl = 175;
            platfrom.Name = "e2d";
            
            return platfrom;
        }
    }
}`

**Server Response to Controller call**

![image](https://user-images.githubusercontent.com/12281546/79216489-441a1c00-7e1b-11ea-8a4d-54c2bfe0b17b.png)

**Server response to GraphQL call**

![image](https://user-images.githubusercontent.com/12281546/79216581-6b70e900-7e1b-11ea-83a0-48fe67585205.png)

**Expected**

 I would expect to see the "Access-Control-Allow-Origin" headers in the response.

**Desktop (please complete the following information):**
 - OS: Windows 10 Running .NET Core 3.0

**Comment by GOVYANSONG** [comment] 2020-04-14 16:09
CORS is pre-flight protocol. Try to put app.UseCors() ahead of app.UseGraphQL("/graphql")

**Comment by michaelstaib** [comment] 2020-04-14 22:10
@GOVYANSONG  is right middleware form a pipeline ... the way you ordered the middleware the authorization / authentication / cors are all done after graphql is already handled meaning it will not happen.

Middleware order is important.

**Comment by michaelstaib** [comment] 2020-04-14 22:11
I am closing this since the issue is answered. If you have follow up questions please go on commenting on this issue.

**Closed by michaelstaib** 2020-04-14 22:11 UTC
Labels: ❓ question

**Comment by Keith3679** [comment] 2020-04-15 00:45
@GOVYANSONG , that fixed it!  Thanks!
