### ISSUE TITLE
GET request without 'Accept: text/html' header results in HC0013 error

### ISSUE THREAD

**Issue by hlovdal** [ChilliCream/hotchocolate#4748] opened 2022-02-10 12:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I ran a curl command to check that I had gotten things configured correctly, but then got HC0013 error. Eventually I also tried the exact same url in the browser, and there it worked ok. So tracking down the difference, it is the precence of an `Accept` header.

### Steps to reproduce

```bash
$ curl http://127.0.0.1:1234/graphql/
$ curl http://127.0.0.1:1234/graphql/ -H 'Accept: text/html'
```

### Relevant log output

```shell
Without `Accept` header:

{"errors":[{"message":"Either the parameter query or the parameter id has to be set.","extensions":{"code":"HC0013"}}]}

With:

<!doctype html><html lang="en"><head><meta charset="utf-8"/>...
```

### Additional Context?

This has actually sort of been reported before in the first comment in #2759, but apparently that issue is about another underlying issue which got resolved without diving into the issue triggering HC0013.

### Product

Hot Chocolate

### Version

HotChocolate.AspNetCore 12.6.0

**Comment by tobias-tengler** [comment] 2022-02-10 12:37
I'm not sure what your problem is. You get the error because Hot Chocolate sees your curl GET request as thr attempto run a GET  query. If you run a proper query you will get a proper response:

```bash
curl localhost:5000/graphql?query={ __typename }
```

If you are sending it with the `Accept` Header, our GraphQL IDE Banana Cake Pop will be served, which is ehat you observe as the HTML result.

Closing this issue for now, as it is working as intended.

**Closed by tobias-tengler** 2022-02-10 12:37 UTC
Labels: 🐛 bug
