### ISSUE TITLE
Registered types are not recognized within nested objects

### ISSUE THREAD

**Issue by emmorts** [ChilliCream/hotchocolate#4482] opened 2021-11-26 09:25 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

While the example provided in the [`HotChocolate.Types.NodaTime` documentation](https://github.com/ChilliCream/hotchocolate/blob/main/website/src/docs/hotchocolate/defining-a-schema/scalars.md#nodatime) works, it seems that using any NodaTime type nested deeper within a returned object fails, due to failure to recognize the type.

I've created a repository that reproduces this issue here: [hotchocolate-nodatime-issue](https://github.com/emmorts/hotchocolate-nodatime-issue).

### Steps to reproduce

1. Install both, `NodaTime` and `HotChocolate.Types.NodaTime` packages
2. Register any NodaTime type with `.AddType<T>()`
3. Create a query which would return a type `T` nested at least 2 levels deep, i.e. 
```csharp
    public class Model
    {
        public InnerModel AnotherModel { get; set; }
    }
    
    public class AnotherModel 
    {
        public Instant Time { get; set; }
    }
    
    public class Queries {
        public IList<Model> GetModels() {...}
    }
```
4. Start the server and try to execute the query

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. For more details look at the `Errors` property.

      1. The type of the member Time of the declaring type AnotherModel is unknown
       (HotChocolate.Data.Filters.FilterInputType<Data.AnotherModel>)

         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.3.2

**Comment by emmorts** [comment] 2021-11-26 09:29
I've realized that there's another issue regarding the same bug here https://github.com/ChilliCream/hotchocolate/issues/4417 .

**Comment by michaelstaib** [comment] 2021-11-26 21:27
There is actually no issue with your project. HotChocolate only automatically infects public properties and public methods as resolvers. The InstantModel is a class with only fields. Once you make it a property it works just fine.

Closing the issue since this is expected behaviour.

**Closed by michaelstaib** 2021-11-26 21:27 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Scalars

**Comment by emmorts** [comment] 2021-11-28 14:52
@michaelstaib, apologies, it seems I may have misidentified the cause in that case. I've updated the issue repository isolating the actual cause, namely `UseFiltering` attribute. It seems that it is that, which is failing to recognize the types.
