### ISSUE TITLE
Stitching: Unexpected errors EXEC_NON_NULL_VIOLATION

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/hotchocolate#3229] opened 2021-03-09 19:03 UTC
# Stitching: Unexpected errors EXEC_NON_NULL_VIOLATION

Please find attached two projects with the reproducible issue.

- `accounts` runs on port 5051
- `gateway` runs on default 5000 and 5001

The project and service `accounts` introduces the following schema:

```graphql
schema {
  query: Query
}

type Query {
  users(ids: [String!]!): [User]!
}

type User {
  id: String!
  name: String!
}
```

The following query with one missing id of the specified three

```graphql
query Users {
  users(ids: ["1", "missing", "2"]) {
    name
  }
}
```

produces the expected result `[user1, null, user2]`:

```json
{
  "data": {
    "users": [
      {
        "name": "Ada Lovelace"
      },
      null,
      {
        "name": "Alan Turing"
      }
    ]
  }
}
```

The project and service `gateway` stitches the single schema `accounts`
add defines the stitched schema as

```graphql
type Query {
  users(ids: [String!]!): [User]!
  @delegate(schema: "accounts", path: "users")
}
```

## Actual result

Now the same query:

```graphql
query Users {
  users(ids: ["1", "missing", "2"]) {
    name
  }
}
```

produces the same result `[user1, null, user2]`
but with unexpected errors EXEC_NON_NULL_VIOLATION on the field `name`:

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "users",
        1,
        "name"
      ],
      "extensions": {
        "code": "EXEC_NON_NULL_VIOLATION"
      }
    }
  ],
  "data": {
    "users": [
      {
        "name": "Ada Lovelace"
      },
      null,
      {
        "name": "Alan Turing"
      }
    ]
  }
}
```

If `User` has other non-null fields and more of them are used in the query,
then we get more errors, one per each such field.

## Expected result

The query works without errors and returns the same result as not stitched service:

```json
{
  "data": {
    "users": [
      {
        "name": "Ada Lovelace"
      },
      null,
      {
        "name": "Alan Turing"
      }
    ]
  }
}
```

***

v11.0.9

[StitchingIssue2.zip](https://github.com/ChilliCream/hotchocolate/files/6110852/StitchingIssue2.zip)

**Comment by nightroman** [comment] 2021-03-12 10:50
The actual use case has slightly worse variation of this issue. Namely, if we allow nullable fields then instead of returning null on missing id, HC instantiates and returns an object with null fields. This is rather incorrect result (comparing to correct expected result + unexpected errors).

For some reason this variation is not reproducible with a trivial case like attached.

**Comment by nightroman** [comment] 2021-03-17 18:07
Acknowledge, add to a milestone? :)

**Comment by nightroman** [comment] 2021-03-24 12:58
Here is the project for the latest v11.1.rc0, same issue.
[StitchingIssue2_v11.1.rc0.zip](https://github.com/ChilliCream/hotchocolate/files/6197353/StitchingIssue2_v11.1.rc0.zip)

**Comment by nightroman** [comment] 2021-05-03 10:54
[Issue-3229-unexpected-null-error.zip](https://github.com/ChilliCream/hotchocolate/files/6414391/Issue-3229-unexpected-null-error.zip)
Here is the project for the latest v11.2.2 same issue.

**Comment by nigel-sampson** [comment] 2021-06-01 02:09
We're seeing the above behavior in our gateway services as well.

**Comment by nightroman** [comment] 2021-11-12 19:58
HC v12.2.1, same issue.

**Comment by nightroman** [comment] 2022-05-04 11:25
Dear stale bot, could you please fix this?
v12.8.2 shows the same issue.

**Comment by michaelstaib** [comment] 2022-05-04 11:41
Closing this since we have this covered in the new stitching engine for 13

**Closed by michaelstaib** 2022-05-04 11:41 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Stitching

**Comment by nightroman** [comment] 2022-05-06 20:30
> Closing this since we have this covered in the new stitching engine for 13

Thank you for the update. The issue is a real pain. We hope v13 is coming soon...

**Comment by nightroman** [comment] 2023-04-12 15:22
@michaelstaib The bug is not fixed in v13 and I cannot reopen it. Should I create a new the same?

**Comment by MvnTruong** [comment] 2023-11-29 14:54
Confirmed, this issue hasn't been fixed in v13. Could we re-open this issue? @michaelstaib

**Comment by RobAltium** [comment] 2023-11-29 17:07
@michaelstaib - please can you advise?  Should this issue be reopened or is there another for v13?  We have real customers who have hit this issue and are stuck.  We're on v13.7.0.  Thanks.

**Comment by nightroman** [comment] 2024-02-28 20:07
I can see the same problem in HC 13.9.

@michaelstaib
Should I open another issue or you reopen this? It is an issue and should exist / be opened.

**Comment by nightroman** [comment] 2024-03-12 00:06
@michaelstaib I am going to open a new issue if this one stays closed and silent.
I think it's fair because the issue exists in v13 in spite of:

> Closing this since we have this covered in the new stitching engine for 13

**Comment by michaelstaib** [comment] 2024-03-13 18:50
As stated we phased stitching out and will not support it any further ... the migration path is to use fusion as we are building fusion on top of the composite schema spec.
