### ISSUE TITLE
Interfaces are removed if not explicitly referenced when setting RemoveUnreachableTypes = true

### ISSUE THREAD

**Issue by mvestergaard** [ChilliCream/hotchocolate#1669] opened 2020-04-08 21:09 UTC
With setting `RemoveUnreachableTypes = true`
A C# interface is used to either define a GraphQL interface, or a union type, and the interface is not used as the value of any field.
The interface is removed from the resulting schema. It can even lead to an invalid schema, where the types reference the interface, which is not there.

**Comment by benmccallum** [comment] 2020-05-29 08:49
Here's where I've hit this. Some types to hit the ground running. In my case I can't have `Page` implement `IPage`, because it comes from a downstream service, but I like the strongly-typed nature of the `IPage` backing the `PageInterface`. 

```c#
public interface IPage { string Title { get; set; } }

public class Page { public string Title { get; set; } = "lol"; }

public class PageInterface : InterfaceType<IPage> { }

public class ArticlePage : ObjectType<Page>
{
    protected override void Configure(IObjectTypeDescriptor<T> descriptor)
    {
        descriptor.Implements<PageInterface>();
    }
}
```

Hope that helps.

**Comment by michaelstaib** [comment] 2020-05-29 10:51
Yeah, the issue is that we look for types exposed through fields which is not enough. We also need to look at implements and typesets from unions.

**Comment by michaelstaib** [comment] 2021-02-18 20:02
This is now fixed.

**Closed** 2021-02-19 00:02 UTC
Labels: :beetle: bug, 🌶 hot chocolate
