### ISSUE TITLE
Projections don't work with NodeResolver

### ISSUE THREAD

**Issue by plhester** [ChilliCream/hotchocolate#5551] opened 2022-11-17 14:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a resolver that is also a NodeResolver. 

    [UseDbContext(typeof(VisionLiveContext))]
    [NodeResolver]
    [UseFirstOrDefault]
    [UseProjection]
    public async Task<IQueryable<User>?> GetUser(Guid id, [ScopedService] VisionLiveContext ctx)
    {
        return ctx.VisionWebUsers.Where(x => x.UserGuid == id);
    }

### Steps to reproduce

These 2 queries call the same resolver and should return same output. However, the nested relations are missing when calling the Node one.

query User($id: ID!) {
  user(id: $id) {
    ...userFields
  }
}

query Node($id: ID!) {
  node(id: $id) {
      ...userFields
  }
}

fragment userFields on VisionWebUser {
  id
  userGuid
  userId
  displayName
  userDepartments(
    where: {
      and: [
        { dept: { hospital: { defunct: { eq: "N" } } } }
        { dept: { defunct: { eq: "N" } } }
      ]
    }
    order: { dept: { hospital: { hospitalName: ASC }, deptName: ASC } }
  ) {
    dept {
      hospital {
        id
        hospitalId
        name: hospitalName
      }
      id
      deptId
      name: deptName
      ccsprofiles(
        where: { defunct: { eq: false } }
        order: { ccsprofileName: ASC }
      ) {
        ccsprofileId
        ccsprofileName
        isDeptDefault
      }
      complianceProfiles(
        where: { isDefunct: { eq: false } }
        order: { name: ASC }
      ) {
        complianceProfileId
        name
        isDefault
      }
      complications(where: { isDefunct: { eq: false } }, order: { name: ASC }) {
        complicationId
        name
        isEnabled
      }
      icuBeds: beds(order: { name: ASC }) {
        id
        bedId
        name
        connections {
          connectionId
          name
        }
      }
      qwsLocations: viperGroups(
        where: { defunct: { eq: "N" } }
        order: { groupName: ASC }
      ) {
        groupId
        groupName
      }
    }
  }
}

### Product

Hot Chocolate

### Version

13.0.0-preview.80

**Comment by glen-84** [comment] 2022-11-17 20:07
Duplicate of #5439.

/cc @PascalSenn

**Comment by michaelstaib** [comment] 2022-11-19 19:27
Closing this in favor of https://github.com/ChilliCream/hotchocolate/issues/5439.

**Closed** 2022-11-19 19:27 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ hot chocolate, Area: Data
