### ISSUE TITLE
Not respected case for subscription results

### ISSUE THREAD

**Issue by AlwaysHC** [ChilliCream/hotchocolate#5574] opened 2022-12-01 18:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello everyone,
I have a problem with subscriptions and field names case.
I'm using a derived class from DefaultNamingConventions to get field names case for queries and mutations as PascalCase and... it works.
I supposed the same for subscriptions but I receive incoherent results:
The request accepts fields in PascalCase but the data received from the subscriptions are always in camelCase.
What am I missing?

### Steps to reproduce

1. Declare and use a class to convert the fields in PascalCase:
public class NamingConventions: DefaultNamingConventions {
    public override NameString GetMemberName(MemberInfo member, MemberKind kind) {
        NameString B = base.GetMemberName(member, kind);
        if (member.DeclaringType != null
            && (member.DeclaringType == typeof(Query)
                || member.DeclaringType == typeof(Mutation)
                || member.DeclaringType == typeof(Subscription)
                || member.DeclaringType.Name.EndsWith("Query")
                || member.DeclaringType.Name.EndsWith("Mutation")
                || member.DeclaringType.Name.EndsWith("Subscription"))) {
            return B;
        }
        else {
            return new(string.Concat(B.Value[..1].ToUpper(), B.Value.AsSpan(1)));
        }
    }

    public override NameString GetArgumentName(ParameterInfo parameter)
         => parameter.Name == null ? base.GetArgumentName(parameter) : new(string.Concat(parameter.Name[..1].ToUpper(), parameter.Name.AsSpan(1)));
}

2. Declare a subscription
3. When subscription will accept fields in PascalCase but the result will be in camelCase

### Relevant log output

```shell
Request:

subscription {
  comments {
    CommentId
    Content
  }
}

Result:
{
  "data": {
    "comments": {
      "commentId": "123",
      "content": "abc"
    }
  }
}
```

### Product

Hot Chocolate

### Version

12.*

**Comment by AlwaysHC** [comment] 2022-12-01 22:37
Meanwhile I'm trying this workaround:
subscription {
  comments {
    commentid: CommentId
    content: Content
  }
}
in order to align the case of the request and the result

**Comment by michaelstaib** [comment] 2022-12-01 22:53
Not sure really ... there is no difference in the handling of subscription... all of these are object types.  So, you actually could better use the kind.

**Comment by AlwaysHC** [comment] 2022-12-02 06:47
This is the SDL generated by HC

type Comment {
  CommentId: Int!
  Content: String!
}

type Subscription {
  comments: Comment
}

So, instead of:
{
  "data": {
    "comments": {
      "commentId": "123",
      "content": "abc"
    }
  }
}
I excepted:
{
  "data": {
    "comments": {
      "CommentId": "123",
      "Content": "abc"
    }
  }
}

**Comment by AlwaysHC** [comment] 2022-12-02 07:54
> Not sure really ... there is no difference in the handling of subscription... all of these are object types. So, you actually could better use the kind.

I couldn't reach my desired naming convention using only the kind parameter.
Anyway, the problem is that queries and mutations results are returned following the defined naming convention (as SDL states) and subscriptions don't

**Comment by AlwaysHC** [comment] 2022-12-02 11:39
The attribute
[GraphQLName("Content")]
is ignored too. The response of the subscription is always camelCase

**Comment by michaelstaib** [comment] 2022-12-08 12:57
can you create a repro ... a project that shows your problem and upload it to the issue?

**Comment by AlwaysHC** [comment] 2022-12-08 15:59
![image](https://user-images.githubusercontent.com/2215615/206495126-ea77c597-4d24-4a09-8f8b-ff2f65b0c3de.png)

https://github.com/AlwaysHC/HotChocolateNamingConvention

**Comment by michaelstaib** [comment] 2022-12-12 10:12
So,

I looked into it and it works correctly. The issue is in your code. The condition you have will always return the camelCase if the member is on one of the root types. 

I am closing this issue since the naming convention works as expected and the issue is with the code you have posted.

Another thing here.... if your code is already PascalCase .... why do you first let the base make it camelCase to just make it PascalCase again?

**Closed** 2022-12-12 10:12 UTC
Labels: ❓ question, 🌶️ hot chocolate
