### ISSUE TITLE
Value cannot be null for declaryingType when visting FieldInfo

### ISSUE THREAD

**Issue by ccampbellclearesult** [ChilliCream/hotchocolate#405] opened 2018-12-19 18:33 UTC
Hello all! I'm experiencing the following exception in my setup:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: declaringType
   at HotChocolate.Validation.FieldSelectionMergingVisitor.FieldInfo..ctor(IType declaringType, FieldNode field)
   at HotChocolate.Validation.FieldSelectionMergingVisitor.VisitField(FieldNode field, IType type, ImmutableStack`1 path)
   at HotChocolate.Validation.QueryVisitor.VisitSelectionSet(SelectionSetNode selectionSet, IType type, ImmutableStack`1 path)
   at HotChocolate.Validation.QueryVisitor.VisitOperationDefinition(OperationDefinitionNode operation, ImmutableStack`1 path)
   at HotChocolate.Validation.FieldSelectionMergingVisitor.VisitDocument(DocumentNode document, ImmutableStack`1 path)
   at HotChocolate.Validation.QueryVisitorValidationErrorBase.Validate(ISchema schema, DocumentNode queryDocument)
   at HotChocolate.Validation.QueryValidator.Validate(DocumentNode query)
   at HotChocolate.Execution.QueryExecuter.CreateQueryInfo(String queryText)
   at HotChocolate.Runtime.Cache`1.GetOrCreate(String key, Func`1 create)
   at HotChocolate.Execution.QueryExecuter.ExecuteInternalAsync(QueryRequest request, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.HandleRequestAsync(HttpContext context, QueryExecuter queryExecuter)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

My startup:
```
services.AddGraphQL(serviceProvider => Schema.Create(options =>
{
    options.RegisterServiceProvider(serviceProvider);
    options.RegisterQueryType<ObjectType<GraphQLRepository>>();
    options.RegisterType<InputObjectType<MapDefinition>>();
}));
```

My types:
```
public class GraphQLRepository
{
    private DbContext dbc;

    public GraphQLRepository(DbContext dbContext)
    {
        dbc = dbContext;
        productMatcher = matcher;
    }

    // This works!
    public async Task<List<EntityFrameworkType>> EntityFrameworkType() => await dbc.EntityFrameworkType.ToListAsync();

    // This produces the declaringType cannot be null exception.
    public async Task<int> AddNewMap(MapDefinition mapDefinition)
    {
        return 1;
    }
}

public class MapDefinition
{
    public int Id { get; set; }
}
```

I think I'm missing a fundamental concept here...trying to figure it out through the docs and what not. I believe it has something to do with parsing the MapDefinition argument of AddNewMap. I've tried IType, and Object/InputObject inheritance wrappers. I've also enabled trace level logs in appSettings. Is there any way I can drill deeper?

**Comment by michaelstaib** [comment] 2018-12-19 18:42
Which version of hotchocolate are you using?

**Comment by ccampbellclearesult** [comment] 2018-12-19 18:50
Ah yes! I'm using version 0.6.11.

**Comment by michaelstaib** [comment] 2018-12-19 18:55
Ok, I will have a look at it.

**Comment by michaelstaib** [comment] 2018-12-19 21:04
Hi, I have setup a little test server but cannot reproduce the error... could you also send me the query. that you are sending to the server?

Mine looks something like this

```GraphQL
{
  addNewMap(mapDefinition:{id:1})
}
```

**Comment by michaelstaib** [comment] 2018-12-19 21:06
I set my server up like this:

```csharp
 public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGraphQL(sp => Schema.Create(c =>
            {
                c.RegisterServiceProvider(sp);
                c.RegisterQueryType<ObjectType<GraphQLRepository>>();
                c.RegisterType<InputObjectType<MapDefinition>>();
            }));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // enable this if you want tu support subscription
            // app.UseWebSockets();
            app.UseGraphQL();
            app.UseGraphiQL();
        }
    }

    public class GraphQLRepository
    {

        public GraphQLRepository()
        {

        }


        // This produces the declaringType cannot be null exception.
        public async Task<int> AddNewMap(MapDefinition mapDefinition)
        {
            return 1;
        }
    }

    public class MapDefinition
    {
        public int Id { get; set; }
    }
```

**Comment by ccampbellclearesult** [comment] 2018-12-19 21:18
Hello, my GraphQL query looks like this:
```
mutation
{
  addnewMap(mapDefinition: { id: 1 })
}
```

Leaving out mutation results in an error:
The field `addnewMap` does not exist on the type `GraphQLRepository`.

I admit I'm not well versed in GraphQL verbs.

I think our setups look the same.

**Comment by michaelstaib** [comment] 2018-12-19 22:04
Ah, if you want that as mutation than you have to declare your type as mutation. You registered it as query. Still there should not be an exception like this. Try RegisterMutationType

**Comment by ccampbellclearesult** [comment] 2018-12-19 22:37
Hello, how do I properly register and query a class like this?

```
    public class MapDefinition
    {
        public MapOptions Options { get; set; }
        public List<ColumnMap> ColumnMaps { get; set; }
    }
```

The List is giving me some trouble.

**Comment by michaelstaib** [comment] 2018-12-20 08:45
> I'll head on over to the GraphQL docs.

[GraphQL.org](https://graphql.org/learn/) is a good place to start. 
We have created an example server that implements their demo schema.
[HotChocolate StarWars Server](https://hotchocolate.io/docs/example-star-wars-code-first)


> I admit I'm not well versed in GraphQL verbs.

In GraphQL you have basically three root types: Query, Mutation, Subscription

Queries is for read-only data consumption and all fields of a query are resolved in-parallel
Mutations are for modifying data. The top-level mutation fields are resolved serial.
Subscriptions represents queries that open up a response stream, basically it is for events/messages.

I think you should first read through the GraphQL.org examples because there is a lot more to know. We are currently working on a tutorial that explains those things but it is not ready yet. So, GraphQL.org is the best place to get stated.

**Comment by michaelstaib** [comment] 2018-12-20 08:52
> Hello, how do I properly register and query a class like this?

Let's say we take you initial example....

Then map data. would be an InputObjectType. So a query with an InputObjectType payload would look like the following:

```GraphQL
{
  addnewMap(mapDefinition: { options: { field1: "abc" field2: 123 } columnMaps:[ { field1: "abc" field2: 123 } ]  })
}
```

GraphQL does not need commas to delimit fields.

So for the next thing I will use the following schema:

```GraphQL
type Query {
  foo: [Foo]
}

type Foo {
  bar: String
}
```

So, the query to ask for the list is the same if it were a complex type (ObjectType/InterfaceType)

```GraphQL
{
 foo {
   bar
 }
}
```

**Comment by michaelstaib** [comment] 2018-12-20 08:53
I will close this issue now and hope the infos helped you.... have fun learning GraphQL :)

**Closed by michaelstaib** 2018-12-20 08:53 UTC
Labels: question

**Comment by michaelstaib** [comment] 2018-12-20 08:55
I have opened a new issue for the nullrefexception.... we will fix that with the next release. Although the query was invalid there should never be a nullrefexception from the system. Thanks for reporting that.
