### ISSUE TITLE
Azure Function isolated template is not compatible with Stitching.Redis library 

### ISSUE THREAD

**Issue by ghobakhlou** [ChilliCream/hotchocolate#5468] opened 2022-10-06 04:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My case is that I wanted to have an azure function as GraphQl gateway which is only available on version 13 `(HotChocolate.AzureFunctions.IsolatedProcess)` , and apparently the `HotChocolate.Stitching.Redis` which is referred in https://chillicream.com/docs/hotchocolate/distributed-schema/schema-federations has been removed in version 13.

Therefore, to have an azure function running as a GraphQL gateway, I had to use HotChocolate.Stitching.Redis which is not compatible with HotChocolate.AzureFunctions.IsolatedProcess. 

It complains about NameString type that has been removed from the Abstraction library. 

`var host = new HostBuilder()
    .ConfigureServices(services =>
    {
        services.AddHttpClient("Accounts", c => c.BaseAddress = new Uri("http://localhost:5051/graphql"));
        services.AddSingleton(ConnectionMultiplexer.Connect("localhost:7000"));
    })
    .ConfigureFunctionsWorkerDefaults()
    .AddGraphQLFunction(b => b.AddQueryType<Query>().AddRemoteSchemasFromRedis("Demo", sp => sp.GetRequiredService<ConnectionMultiplexer>()))
    .Build();

host.Run();`

### Steps to reproduce

1. run donet new graphql-azf-ip to install azure function template
2. add latest HotChocolate.Stitching.Redis 
3. add AddRemoteSchemasFromRedis to program.cs as explained above

### Relevant log output

```shell
Project fails to build with error `NameStrig type is missed from Abstraction library`
```

### Product

Hot Chocolate

### Version

13.0.0Preview66

**Comment by michaelstaib** [comment] 2022-10-09 23:09
The issue is that we have not updated the stitching libs yet. We will do that soon. I am closing this issue.

**Closed by michaelstaib** 2022-10-09 23:09 UTC
Labels: 🐛 bug
