### ISSUE TITLE
Operation cache does not work properly with multiple schemas.

### ISSUE THREAD

**Issue by SebastianStehle** [ChilliCream/hotchocolate#2954] opened 2021-01-28 21:36 UTC
**Describe the bug**
When you register multiple schemas and endpoints the two schemas seem to interfere.

I have a reproducible here: https://github.com/SebastianStehle/dynamic-schemas/blob/main/WebApplication1/Startup.cs
Please ignore the other stuff inside the `#`if`, as it is for another test.

**To Reproduce**
1. Go to 'https://localhost:5001/graphql/foo/'
2. Run the following query 
```
query {
  both {
    value
  }
}
```
3. Go to 'https://localhost:5001/graphql/bar/'
4. Run the same query again.

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "both"
      ],
      "extensions": {
        "message": "The parent cannot be casted to WebApplication1.Startup+QueryBar.",
        "stackTrace": "   at HotChocolate.Execution.Processing.MiddlewareContext.Source[T]()\r\n   at HotChocolate.Execution.Processing.MiddlewareContext.Parent[T]()\r\n   at lambda_method46(Closure , IResolverContext )\r\n   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ],
  "data": {
    "both": null
  }
}
```

**Expected behavior**
The 2 schemas should be strictly separated, but something gets cached.

**Desktop (please complete the following information):**
 - Version 11.0.9

**Additional context**

**Comment by SebastianStehle** [comment] 2021-01-29 09:02
I have extended my test with a code first approach

If you go to 

https://localhost:5001/graphql/fooType/ and then https://localhost:5001/graphql/barType/ then the value from the first used schema is returned.

**Comment by michaelstaib** [comment] 2021-02-01 16:47
The issue is with the schema interceptor. I will close this issue since this is not a bug. We will have a look at your approach together on Friday.

**Comment by SebastianStehle** [comment] 2021-02-01 18:00
Why is it with the schema interceptor? 

I have disabled them for this test, so I have only registerd two schemas

```
services.AddGraphQLServer("myFoo")
    .AddQueryType<QueryFoo>();
services.AddGraphQLServer("myBar")
    .AddQueryType<QueryBar>();
services.AddGraphQLServer("myFooType")
    .AddQueryType<QueryFooType>();
services.AddGraphQLServer("myBarType")
    .AddQueryType<QueryBarType>();
```

and a few endpoints

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();

    endpoints.MapGraphQL("/graphql/foo", "myFoo");
    endpoints.MapGraphQL("/graphql/bar", "myBar");
    endpoints.MapGraphQL("/graphql/fooType", "myFooType");
    endpoints.MapGraphQL("/graphql/barType", "myBarType");
});
```

Is this supported or not? If it is not supported, why can I define the schema name?

**Comment by SebastianStehle** [comment] 2021-02-01 20:19
I simplified my example in this branch: https://github.com/SebastianStehle/dynamic-schemas/tree/simple

I also checked all the caches and when I turn off the IPreparedOperationCache it works as expected. I think it does not has anything to do with my special use case.

**Comment by michaelstaib** [comment] 2021-02-01 21:23
@SebastianStehle you are right. Just checked it. The issue is if the schemas essentially have an overlap so that the same queries is used with all of the schemas. In this case the query has is the same. I will issue a fix for this.

**Closed** 2021-03-18 12:57 UTC
Labels: :beetle: bug, 🌶 hot chocolate
