### ISSUE TITLE
ExtendServiceType not adding `extend` keyword to type

### ISSUE THREAD

**Issue by cli00004** [ChilliCream/hotchocolate#5015] opened 2022-04-29 01:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`ExtendServiceType` attribute for ApolloFederation is not adding the extend keyword to the type which results in Rover publish error 
![image](https://user-images.githubusercontent.com/94087985/165871716-11711e6d-dc43-4a3d-af0f-b8accc820ae9.png)
![image](https://user-images.githubusercontent.com/94087985/165871729-a9b3d2a1-78ed-452d-a6cc-24ddd025b2b9.png)

Rover:
![image](https://user-images.githubusercontent.com/94087985/165871787-fa87bef0-816a-43fd-bd00-674303c86dc9.png)

### Steps to reproduce

1. Create a type in a subgraph and annotate it with `ExtendServiceType`
2. Run the application and check the generated schema, the type is without the `extend` keyword in the front

### Product

Hot Chocolate

### Version

12

**Comment by abc-moviestarplanet** [comment] 2022-05-02 08:10
Running into the same issue.

I think I narrowed the issue down to this part of the code: https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/ApolloFederation/src/ApolloFederation/FederationSchemaPrinter.OutputTypes.cs#L28

In that case, the node name should be prefixed by `extend`.

**Comment by michaelstaib** [comment] 2022-05-02 12:38
The code you pointed to looks correct ... we return an ObjectTypeExtensionNode which is correct. Can you create a small repro and tell me which type is not correctly exposed as a type extension?

**Comment by abc-moviestarplanet** [comment] 2022-05-02 13:23
Yes that's true.

The repro steps were already described, but I made a very tiny repo in .NET 6 that reproduces the issue in case it helps: https://github.com/abcfantasy/HotChocolateMissingExtend/tree/main

I put the SDL output (returned from `/graphql?sdl`) in the README. The `Customer` type is missing the `extend` keyword.

**Comment by 1337vida** [comment] 2022-05-02 13:50
Hello @abc-moviestarplanet , I've been looking to contact you. Can you please check your email?

**Comment by abc-moviestarplanet** [comment] 2022-05-03 14:39
Okay, I think I found the source of the confusion - and how to solve it (FYI @cli00004 ).

The endpoint `/graphql?sdl` returns the subgraph schema with all the apollo federation metadata and directives (and with the missing `extend` keyword). This is **not** the output that should be used to push to the schema registry.

If I instead get the SDL by querying the subgraph using a GraphQL query itself:
```
query {
  _service {
    sdl
  }
}
```

The result of that omits apollo federation metadata, and correctly includes the `extend` keyword. This is the SDL that should be pushed to the schema registry.

**Comment by cli00004** [comment] 2022-05-03 21:17
Thanks @abc-moviestarplanet. But then this is a little tricky as we can't easily get the schema at cicd pipeline, seems we have to then write a query for this. Currently what I did is add a custom directive `@extends`  to the entity i'd like to extend, this is also supported by Apollo https://www.apollographql.com/docs/federation/federation-spec/#fetch-service-capabilities , but I would hope the `ExtendServiceType ` would just do this already

**Comment by michaelstaib** [comment] 2022-05-03 22:32
@abc-moviestarplanet this is exactly what the apollo federation spec specifies. There is the actually schema and the subgraph schema.

@cli00004 you can actually there is an apollo federation printer that you can use.

Closing the issue since this is not a bug.

**Closed by michaelstaib** 2022-05-03 22:32 UTC
Labels: ❓ question

**Comment by cli00004** [comment] 2022-05-03 22:44
@michaelstaib Oh right, can you please link me to the function I should use for Apollo Federation printer?
