### ISSUE TITLE
Enums prefixed with underscore get them removed

### ISSUE THREAD

**Issue by JacobvanP** [ChilliCream/hotchocolate#4779] opened 2022-02-18 12:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our code we have an enum that has values prefixed with an _ resulting a schema like this:
```graphql
enum AdnRes {
  _1
  _2
  _3
  _4
  A
  B
  D
  E
  F
  I
  N
  O
  S
  U
  W
}
```

When trying to load this into strawberry shake it removes the underscore resulting in invalid c#.

### Steps to reproduce

1. Try to create a strawberry shake client with above schema
2. Build the project

### Relevant log output

```shell
CSC : error SS0006: `` is not a valid GraphQL type name. (Parameter 'value')
```

### Product

Strawberry Shake

### Version

12.6.0

**Comment by PascalSenn** [comment] 2022-02-18 13:02
Closes as this is a duplicate of https://github.com/ChilliCream/hotchocolate/issues/4771

**Closed as completed by PascalSenn** 2022-02-18 13:02 UTC
Labels: 🐾 duplicate, 🌶️ strawberry shake
