### ISSUE TITLE
StrawberryShake: References from generated code are not found in other project ?

### ISSUE THREAD

**Issue by StefH** [ChilliCream/hotchocolate#3401] opened 2021-04-01 06:39 UTC
**Describe the bug**
When following the tutorial at (https://chillicream.com/docs/strawberryshake/get-started), but instead of using 1 project which contains the Blazor project and the code generation, I used two projects.

However the references from the second project are not resolved in the first (Blazor) project in VS2019, although the code compiles?

![image](https://user-images.githubusercontent.com/249938/113253131-20b6de00-92c5-11eb-9e6b-7e55b9396e37.png)

**To Reproduce**
Create a GraphQL project:
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".config\dotnet-tools.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.0.0-preview.0" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="12.0.0-preview.0" />
  </ItemGroup>

</Project>
```

Create a BlazorWebAssemblyproject:
``` xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
		<PackageReference Include="System.Net.Http.Json" Version="5.0.0" />

	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\xxx.GraphQL\xxx.GraphQL.csproj" />
	</ItemGroup>

</Project>
```

**Expected behavior**
References are found.

**Desktop (please complete the following information):**
 - Windows 10
 - Visual Studio 2019 Preview (latest)
 - StrawberryShake.Tools --version 12.0.0-preview.0

**Comment by 4minus** [comment] 2022-03-30 06:48
Same problem here, i'm using strawberryshake in two .net5.0 projects that reference each other, and Rider IDE as well as Visual Studio 2022 are telling me the references where missing despite beeing referenced to each other.
Although the projects can be build, it's kind of anoying because intellisense won't work.

![image](https://user-images.githubusercontent.com/12270786/160768840-b75878bb-831b-4646-a408-4c1509fd6557.png)

**Comment by tobias-tengler** [comment] 2022-03-30 08:01
This sounds more like an issue with the IDEs to me. Source Generator support is still not fully there yet in my own experience.
That being said, have you tried the latest preview bits (v13)? I know that @michaelstaib changed some things around the code generation and it should be more resilient now. Hopefully this solves your problem already :)

**Comment by tobias-tengler** [comment] 2022-03-30 08:05
I'm closing this now, since the issue is pretty old and hasn't gotten much attention. If you still encounter this issue with v13, kindly raise a new issue with a proper reproduction.
Also try researching if this cross-project thing is a well known issue with other source generators as well. It feels to me like it is not an issue of how the generator was implemented, but the IDE support not being 100% reliable...

**Closed by tobias-tengler** 2022-03-30 08:05 UTC
Labels: 🌶️ strawberry shake

**Comment by 4minus** [comment] 2022-03-30 08:09
Thank you @tobias-tengler for you fast answer. I'm working on v12.6 right now, i'll give the preview a try.
