### ISSUE TITLE
ObjectType cannot contain more than one UUID field

### ISSUE THREAD

**Issue by jamiewinder** [ChilliCream/hotchocolate#5136] opened 2022-06-08 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't seem to add more than one `UUID` field to my object type. 

```c#
public record MyObject(Guid Uuid, string Name, Guid? AnotherGuid);

public class MyGraphType : ObjectType<MyObject>
{
    protected override void Configure(IObjectTypeDescriptor<MyObject> descriptor)
    {
        descriptor
            .Name("MyObject")
            .BindFieldsExplicitly();

        descriptor
            .Field(a => a.Uuid)
            .Name("uuid")
            .Type<NonNullType<UuidType>>();

        descriptor
            .Field(a=> a.Name)
            .Name("name")
            .Type<StringType>();

        /*
        descriptor
            .Field(a=> a.AnotherUuid)
            .Name("anotherUuid")
            .Type<UuidType>();
        */
    }
}
```
Note part of this is commented out.  As you'd expect, this creates a graph with a type:
```graphql
type MyObject {
    uuid: UUID!
    name: String
}
```
If I uncomment the code, it creates a graph with the following type:
```graphql
type MyObject {
    name: String
    anotherUuid: UUID
}
```
The original UUID field seems to be getting overwritten when a second field also of type UUID is defined.

### Product

Hot Chocolate

### Version

12.0.0

**Comment by michaelstaib** [comment] 2022-06-08 21:22
I cannot reproduce this behavior. Can you create a small project that shows this issue?

**Comment by michaelstaib** [comment] 2022-06-11 09:19
If you can post a small project showing the  issue we can also have a look.

**Comment by jamiewinder** [comment] 2022-06-11 09:51
I've tried, but it must be some weirdness in the entities (which aren't my code). I've ended up working around it by using an intermediary POCO.

One thing that did occur to me was that both the Uuid properties are `[Key]`s on their respective entities, so something - somehow - might be confusing things by having two Keys on the same graph type, even though they actually come from two different entities.

Just a theory. Either way this isn't an issue for me at the moment, just a curiosity. Thanks.

**Comment by michaelstaib** [comment] 2022-06-11 10:22
We do not inspect EF core specifics... so we do not scan for keys. We just look at the properties and methods of an object.

**Comment by michaelstaib** [comment] 2022-06-11 10:24
I am closing the issue since we cannot get forward on this issue ... if you ever get more insights into it or you can post us the entity code (you can also do that privately on slack) we can further look into the issue.

slack.chillicream.com

**Closed by michaelstaib** 2022-06-11 10:24 UTC
Labels: 🔍 investigate, 🌶️ hot chocolate
