### ISSUE TITLE
Same Class cannot be used for Input and Output

### ISSUE THREAD

**Issue by tsinghammer** [ChilliCream/hotchocolate#187] opened 2018-07-25 07:27 UTC
**Describe the bug**
Hi, I tried to create ObjectTypes from one C# Class, one to be used as an input parameter in a mutation and one to be returned by a query.

**To Reproduce**
The code looks like following:
config.RegisterType<InputObjectType<AddressData>>();
config.RegisterType<ObjectType<AddressData>>();
and 
descriptor.Field(t => t.GetAddressData()).Type<ObjectType<AddressData>>();
for the query.

When starting up the application it brings me an error saying:
HotChocolate.SchemaException: The type `HotChocolate.Types.ObjectType<AddressData>` of field `Queries.addressData` could not be resolved to a valid schema type.

However if I replace it by

config.RegisterType<ObjectType<AddressData2>>();
and 
descriptor.Field(t => t.GetAddressData()).Type<ObjectType<AddressData2>>();

it works like a charm.

**Expected behavior**
Is it intended not to be able to use the same class for input and output types?

**Comment by michaelstaib** [comment] 2018-07-25 07:30
I will have a look at it.

**Comment by michaelstaib** [comment] 2018-07-25 08:02
I have checked it. It works fine. Here is my integration test including the schema:

```csharp

using HotChocolate.Execution;
using HotChocolate.Types;
using Xunit;

namespace HotChocolate.Integration.InputOutputObjectAreTheSame
{
    public class InputOutputObjectAreTheSame
    {
        [Fact]
        public void CheckIfTypesAreRegisteredCorrectly()
        {
            // arrange
            Schema schema = CreateSchema();

            // act
            bool containsPersonInputType = schema
                .TryGetType("PersonInput", out INamedInputType _);
            bool containsPersonOutputType = schema
                .TryGetType("Person", out INamedOutputType _);

            // assert
            Assert.True(containsPersonInputType);
            Assert.True(containsPersonOutputType);
        }

        [Fact]
        public void ExecuteQueryThatReturnsPerson()
        {
            // arrange
            Schema schema = CreateSchema();

            // act
            IExecutionResult result = schema.Execute(@"{
                person(person: { firstName:""a"", lastName:""b""  }) {
                    lastName
                    firstName
                }
             }");

            // assert
            Assert.Null(result.Errors);
            Assert.Equal(Snapshot.Current(), Snapshot.New(result));
        }

        private static Schema CreateSchema()
        {
            return Schema.Create(c =>
            {
                c.RegisterQueryType<Query>();
                c.RegisterType<ObjectType<Person>>();
                c.RegisterType(new InputObjectType<Person>(
                    d => d.Name("PersonInput")));
            });
        }
    }

    public class Person
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }
    }

    public class Query
    {
        public Person GetPerson(Person person)
        {
            return person;
        }
    }

}


```

**Comment by michaelstaib** [comment] 2018-07-25 08:04
It is important that the person input type has a different name than the object type since for graphql they are different types:

> c.RegisterType<ObjectType<Person>>();
                c.RegisterType(new InputObjectType<Person>(
                    d => d.Name("PersonInput")));

**Comment by michaelstaib** [comment] 2018-07-25 08:06
I think I will come into the office after lunch, that I could have a look at your problem. I`ll close this issue since it is not a bug.

**Closed by michaelstaib** 2018-07-25 08:06 UTC
Labels: question

**Comment by tsinghammer** [comment] 2018-07-25 08:44
Yes, it works when I assign a distinct input parameter name.
Thanks!
