### ISSUE TITLE
10.4.0-rc.1 returns 99 instead of 99.0 for Decimal number

### ISSUE THREAD

**Issue by sgabler-solytic** [ChilliCream/hotchocolate#1563] opened 2020-03-17 13:34 UTC
**Describe the bug**
I just upgraded from 10.3.5 to 10.4.0-rc.1 and my tests are now failing

<img width="328" alt="image" src="https://user-images.githubusercontent.com/55686147/76860644-a7844e80-685b-11ea-99c6-06a7541c4070.png">

Here's part of my Type
```csharp
            descriptor.Field(site => site.InstalledCapacity)
                .Description("Installed capacity")
                .Type<NonNullType<DecimalType>>();
```

Which references a `Site`
```csharp
public decimal InstalledCapacity { get; set; }
```

**Expected behavior**
I would expect `99.0`, as before. But maybe this is intentional?

**Comment by sgabler-solytic** [comment] 2020-03-17 13:50
Spent some time debugging, and it doesn't always happen. It only happens when I have a mutation like this:

```
mutation {
  updateSite(site: { id: 1, installedCapacity: 99 }) {
    installedCapacity
  }
}
```

So if I set the value as `99.0` here, the test would probably still work

**Comment by michaelstaib** [comment] 2020-03-17 15:44
Is the result 99, I mean the json result or what exactly?

**Comment by sgabler-solytic** [comment] 2020-03-17 16:00
Yes, the JSON result returns 99. Previously it returned 99.0. Sorry for not making that clear enough @michaelstaib

**Comment by michaelstaib** [comment] 2020-03-17 16:29
We switched the serializer from JSON.NET to System.Text.Json. So it might be that this handles it differently. It is not invalid since 99.0 can be expressed as 99 without losing anything.

**Comment by sgabler-solytic** [comment] 2020-03-18 07:30
That might be an explanation. Strange that it only appears when I manually set the value in a mutation, but not when I fetch the same field via a query (in this case it's 99.0)

**Comment by michaelstaib** [comment] 2020-03-18 08:44
Can you build a small repro?

**Comment by sgabler-solytic** [comment] 2020-03-20 11:12
@michaelstaib I'll try to do that on the weekend. Is there already an existing project I could simply modify to speed things up?

**Comment by michaelstaib** [comment] 2020-03-20 11:57
Awesome, if it turns out to be a bug we will fix it in our 10.4.1 patch release.

**Comment by sgabler-solytic** [comment] 2020-03-23 16:43
I finally had time to take a look. What I did:

I modified the existing StarWars example by switching `Stars` from `int` to `decimal` in `examples/AspNetCore.StarWars/Models/Review.cs`
```csharp
        /// <summary>
        /// The number of stars given for this review.
        /// </summary>
        public decimal Stars { get; set; }
```

Then sending the following mutation:

```graphql
mutation {
  createReview(review: {commentary:"Blabla", stars:4.0}, episode:NEWHOPE) {
    stars
  }
}
```

Which gives me this response:
```json
{
  "data": {
    "createReview": {
      "stars": 4
    }
  }
}
```
Notice the missing `.0` at the end

But if I call the mutation with 4.5, I get this:
```
{
  "data": {
    "createReview": {
      "stars": 4.5
    }
  }
}
```

**Comment by michaelstaib** [comment] 2020-03-27 08:58
So, it is because of the new serializer. But it is not actually wrong so I will close this one. Thanks for your help making sure that this is not a bug.

**Closed by michaelstaib** 2020-03-27 08:58 UTC
Labels: investigate
