### ISSUE TITLE
Using built in filtering uses AND instead of OR

### ISSUE THREAD

**Issue by NickBeukema** [ChilliCream/hotchocolate#1335] opened 2020-01-07 19:31 UTC
**Describe the bug**
I'm having an issue with the built in filtering in HotChocolate. I'm running a query to search over Contacts, checking if the search term is either in the FirstName or the LastName, but the SQL getting run uses an AND, requiring the search term to exist in both the FirstName and the LastName.

**To Reproduce**

On `QueryType.cs`

```
descriptor.Field(t => t.ContactGetAll(default))
    .UseFiltering()
```

The query I'm running
```
query GetAll($searchTerm: String) {
   contactGetAll (where: { firstName_contains: $searchTerm, OR: { lastName_contains: $searchTerm } }) {
      ...BasicContact
   }
}
```

The SQL generated
```
...
WHERE ([c].[FirstName] IS NOT NULL AND (CHARINDEX(N'name', [c].[FirstName]) > 0)) AND ([c].[LastName] IS NOT NULL AND (CHARINDEX(N'name', [c].[LastName]) > 0))
```

**Expected behavior**
I'm expecting the SQL generated to use `OR` functionality, allowing the search term to be in either of the strings, not requiring both.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Docker Image - mcr.microsoft.com/dotnet/core/sdk:3.0)
 - HotChocolate: 10.3.2

Please let me know if any other information is needed.

Thanks!

**Comment by PascalSenn** [comment] 2020-01-07 19:48
We just discussed this on slack. 

_Adrian Frielinghaus_
>This might be the same as something that puzzled me... the OR conditions need to be in an array like so:
OR: [
        {
            lastName_contains: $searchTerm
        },
        {
            lastName_contains: $searchTerm
        }
    ]


_Nick Beukema_

```graphql
contactGetAll (where: { OR: [{ lastName_contains: $searchTerm }, { firstName_contains: $searchTerm }] }) {
}
```
>That is erroring now
>{"0":{"message":"Unexpected Execution Error","locations":[{"line":10,"column":3}],"path":["contactGetAll"]}}
>But it is working with the previously stated query (which now makes sense why it's doing an AND). It also works with each individual filter as well.

**Comment by michaelstaib** [comment] 2020-01-07 19:51
Actually this is not a bug but fully correct.

Let me explain.

The assumption that we have done to make it very easy to use is that the default is `AND`.

Meaning: 

```graphql
{ a: $a b: $b }
```

Will become a simple and query. So for simple queries there is no need to express an AND operator.

of you want an or query this is the way to write it:

```graphql
{ OR: [ { a: $a } { b: $b } ] }
```

And you also can combine this since:

```graphql
{ a: $a OR: [ { b: $b } { c: $c } ] }
```

would become 

```
a = $a AND (b = $b OR c = $c)
```

the above can also be expressed more explicitly:

```graphql
{ AND: [ { a: $a } ] OR: [ { b: $b } { c: $c } ] }
```

and also you can do more complex queries like:

```graphql
{ AND: [ { a: $a } ] OR: [ { b: $b } { AND: [ { c: $c } { d: $d } ] } ] }
```

which would become:

```
a = $a AND (b = $b OR  (c = $c AND d = $d))
```

Does that clarify how the queries work... If you worked with mongo this should be quite familiar.

Hope this helps :)

**Comment by michaelstaib** [comment] 2020-01-07 19:54
Can we close this issue?

**Comment by PascalSenn** [comment] 2020-01-09 01:34
@NickBeukema  I added a issue especially for the bug you observed :+1: 
I will close this issue

**Closed by PascalSenn** 2020-01-09 01:34 UTC
Labels: Filter, question

**Comment by michaelstaib** [comment] 2020-01-09 08:22
I think we also should write Moro docu on the filters. I think I will add a section on how the filters translate to sql.
