### ISSUE TITLE
AddExtensionsFromFile adds /app to path

### ISSUE THREAD

**Issue by lTimeless** [ChilliCream/hotchocolate#968] opened 2019-08-07 17:42 UTC
**Describe the bug**
The "AddExtensionsFromFile"- Method adds "/app" to the filepath . So even creating a folder called "app" will not help, than the error is that it can't find the file "/app/app/Extensions.graphql"
The Error: "System.IO.FileNotFoundException: Could not find file '/app/Extensions.graphql'."

**Expected behavior**
That it does not add "/app" to the path

.AddExtensionsFromFile("./Extensions.graphql") should find the file in the root directory of my asp.net core project

**Additional context**
I'm Using Asp.net core 2.2 and so far everything works besides that. I followed the documantaion and the youtube Video explaining how to schema stitch

**Comment by michaelstaib** [comment] 2019-08-07 18:54
Hi @lTimeless I will have a look.

**Comment by michaelstaib** [comment] 2019-08-07 18:55
https://github.com/ChilliCream/hotchocolate/blob/3e8348399f653b130f4830870eed20430dabe7b4/src/Stitching/Stitching/Extensions/StitchingBuilderExtensions.cs#L109

**Comment by michaelstaib** [comment] 2019-08-07 18:57
I have checked it and this is not in our code base. Have a look at the code. 

Can you try using a fully qualified path?

**Comment by lTimeless** [comment] 2019-08-08 05:36
Hi , if i put the absolute path(C:/.....) in , the /app will still appear in front of it( /app/C:/....).
Thats really weird and I haven't changed anything else, just created an asp.net core 2.2 app and than imported hot chocolate to do schema stitching.

**Comment by michaelstaib** [comment] 2019-08-08 06:13
So, you are on Windows? I will start a VM later and test this... but if you are looking at the actual code you can see that we are just passing the path string to the .net `File` API. 

I think it could also be because you are using `/` instead of `\` on windows. I will check that out.

**Comment by lTimeless** [comment] 2019-08-08 15:58
okay yeah i saw that. Yes im on windows and starting my asp.net core in docker but that shouldn't be a problem right?

**Comment by michaelstaib** [comment] 2019-08-08 16:56
I do not know your setup. I guess the file api is misinterpreting your path. Can you try it without docker and with the proper separators?

**Comment by michaelstaib** [comment] 2019-08-08 16:58
I mean you can also just use the microsoft file api yourself and the same will happen. 

System.IO.File.ReadAllBytes(yourPath)

**Comment by lTimeless** [comment] 2019-08-08 18:49
I will try it without docker and with proper seperators asap .

If I use microsofts file api how do I pass it to the graphql interface?

**Comment by michaelstaib** [comment] 2019-08-08 21:20
This is what we do here:

```
public static IStitchingBuilder AddExtensionsFromFile(
            this IStitchingBuilder builder,
            string path)
        {
            if (builder == null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            if (string.IsNullOrEmpty(path))
            {
                throw new ArgumentException(
                    StitchingResources.ExtensionsFilePath_EmptyOrNull,
                    nameof(path));
            }

            builder.AddExtensions(s =>
                Utf8GraphQLParser.Parse(
                    File.ReadAllBytes(path)));
            return builder;
        }
```

There is nothing we do with the path actually so I think this is something with your setup.


What  I meant with:

> I mean you can also just use the microsoft file api yourself and the same will happen.

The error with the path come from the Microsoft File API.

**Comment by michaelstaib** [comment] 2019-08-09 20:48
Have you got it working?

**Comment by michaelstaib** [comment] 2019-08-10 12:04
I will close this issue since it is not a bug.

We have a slack channel so if you need help further help just get us a message there.

https://join.slack.com/t/hotchocolategraphql/shared_invite/enQtNTA4NjA0ODYwOTQ0LTViMzA2MTM4OWYwYjIxYzViYmM0YmZhYjdiNzBjOTg2ZmU1YmMwNDZiYjUyZWZlMzNiMTk1OWUxNWZhMzQwY2Q

**Closed** 2019-08-10 12:04 UTC
Labels: question
