### ISSUE TITLE
OneOf Input type is incorrect on serialization

### ISSUE THREAD

**Issue by elmanav** [ChilliCream/hotchocolate#4911] opened 2022-04-01 09:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An attempt to serialize a input type marked as OneOf attribute results in the error OneOfMoreThanOneFieldSet (HC0055 - More than one field of the Oneof Input Object is set.). For example, call API IRequestExecutor.ExecuteAsync() with variables. However, exactly 1 field is specified in the object.
Analysis of the parser code (InputParser.ParseObject()) showed that only the count of fields in the object is checked, but the not check NullValueNode. So it's always wrong.

### Steps to reproduce

1. Type with attribute OneOf, for example
```
 [OneOf]
 public class AnimalDataInput
 {
     public string? Cat { get; set; }
     public string? Dog { get; set; }
 }
```
2. Execute request API with explicitly variable
```
var variables = new Dictionary<string, object?>
			{
				{
					"input", new AnimalDataInput()
					{
						Dog = "dog"
					}
				}
			};
var result = await executor.ExecuteAsync(query, variables);
AssertErrors(result);
result.MatchSnapshot();
```

### Relevant log output

```shell
"errors": [
    {
      "message": "More than one field of the Oneof Input Object \u0060AnimalDataInput\u0060 is set. Oneof Input Objects are a special variant of Input Objects where the type system asserts that exactly one of the fields must be set and non-null.",      
      "extensions": {
        "code": "HC0055"
      }
    }
  ]
```

### Product

Hot Chocolate

### Version

12.7.0

**Comment by cliedeman** [comment] 2022-06-06 21:36
I also encountered this. But it only happenend in a test using the Executor directly.

I managed to work around it by Creating Dicts

**Comment by michaelstaib** [comment] 2022-06-08 21:20
This is not a bug. While you can pass in the runtime representation we in the common case expect an ObjectValueNode. A .Net can not discern between null and not set. Closing this issue.

**Closed by michaelstaib** 2022-06-08 21:20 UTC
Labels: 🐛 bug, 🔍 investigate, 🌶️ hot chocolate, Area: Type System
