### ISSUE TITLE
String enum causes exception on startup

### ISSUE THREAD

**Issue by krij0n** [ChilliCream/hotchocolate#1270] opened 2019-12-10 12:58 UTC
Using string enum like this:
`public class StringEnumTestType : EnumType<string>
    {
        protected override void Configure(IEnumTypeDescriptor<string> descriptor)
        {
            descriptor.Value("value").Name("name");
        }
    }`

Causes error on startup: "The name `String` was already registered by another type - Type: String"

**Comment by michaelstaib** [comment] 2019-12-16 21:20
This issue is now fixed with 10.3.0-preview.11

**Closed by michaelstaib** 2019-12-16 21:20 UTC
Labels: bug

**Comment by ademchenko** [comment] 2020-06-22 21:43
The issue can still be reproduced on the current stable release 10.4.3.

**Comment by michaelstaib** [comment] 2020-06-23 05:40
Have you given the type a name? Since the name String is reserved.

**Comment by ademchenko** [comment] 2020-06-25 11:58
@michaelstaib, thanks, it helped but after fixing the name I'm facing another issue:
I have a string property (Type) which I would like to convert to string enum:
`public class PaymentType : ObjectType<Payment>
    {
        protected override void Configure(IObjectTypeDescriptor<Payment> descriptor)
        {
            descriptor.Field(t => t.Type).Type<PaymentKindEnumType>();
        }
    }
 public class PaymentKindEnumType : EnumType<string>
    {
        protected override void Configure(IEnumTypeDescriptor<string> descriptor)
        {
            descriptor.Name("PaymentKind");
            descriptor.Value("deposit").Name("deposit");
            descriptor.Value("withdraw").Name("withdraw");
        }
    }`
and while making the request I get the following error:
PaymentKind cannot parse the given literal of type `StringValueNode`. (Parameter 'literal')",
        "stackTrace": "   at HotChocolate.Types.EnumType.ParseLiteral(IValueNode literal)\r\n   at HotChocolate.Execution.FieldCollector.ParseLiteral(IInputType argumentType, IValueNode value)\r\n   at HotChocolate.Execution.FieldCollector.CreateArgumentValue(FieldInfo fieldInfo, IInputField argument, IValueNode literal)\r\n   at
